- docker/auxiliary/index-k/Dockerfile
- docker/auxiliary/index-k/assets/create-index.sh
- docker/auxiliary/index-k/assets/ls_s2_cog.py
- docker/auxiliary/index-k/assets/update_ranges.sh
- docker/auxiliary/index-k/assets/update_ranges_wrapper.sh
- docker/auxiliary/setup-k/Dockerfile
- docker/auxiliary/setup-k/assets/create-db.sh
- docker/auxiliary/setup-k/assets/create-db.tf
Kubernetes friendly docker images
Currently being tested, will replace the normal aux images after tests complete
> New auxillary images

- docker/auxiliary/index-k/assets/ls_s2_cog.py
Remove un-used deps.
Don't try and index files that have already been indexed.
Give us some stats on index speeds.
> update index script

- datacube_wms/data.py
See https://trac.osgeo.org/gdal/wiki/CloudOptimizedGeoTIFF
> Apply GDAL COG environment settings

- datacube_wms/data.py
Does not support configuration of fuse_func yet, so works for geomedian but not daily WOFS.
> Use dask to thread input file reading

- datacube_wms/_geom.py
- datacube_wms/data.py
- datacube_wms/wms_utils.py
Replaces the read_from_source function (and transform functions) with @Kirill888's read_with_reprojection function.
Read rasterio resampling function from the layer config (allows us to set different resampling methods for datasets where average isn't good enough)
> Replace read_from_source with read_with_resampling

- datacube_wms/cube_pool.py
- datacube_wms/data.py
- datacube_wms/wms_layers.py
This PR changes the exception-based try-finally usage of a Datacube instance from the CubePool into a context manager, which does the release when it falls out of scope or in the event of an exception
Feedback on a better name than "cube" is requested!
> CubePool as a context manager

- README.rst
- datacube_wms/data.py
For all time queries, extend time from earliest possible time in first datetime to latest possible time in final datetime.
> Extend time range in query for GetFeatureInfo requests

- datacube_wms/wms_layers.py
Check for missing datacube product and missing wms extent row when creating product object. If missing, do not create object. Prevents somewhat cryptic errors from occurring when performing GetCapabilities / GetMap on a WMS service.
> Check for missing product / ranges

- datacube_wms/templates/wms_capabilities.xml
Checks for existence of products in platform to allow Terria to process the capabilities document.
> Add conditional block to wms_capabilities template

- datacube_wms/data.py
- tests/test_data.py
Will replace with a "n/a" string to match with nodata values
> Add check for NaN in functions creating JSON object for GetFeatureInfo

- datacube_wms/wcs_utils.py
Backend support for a WMS-like "styles" parameter in WCS, as required for the TerriaJS PR: https://github.com/TerriaJS/terriajs/pull/3170
This is a non-standard extension, but will have no impact on standards-compliant requests.  
If the "styles" parameter in a WCS request contains a valid WMS style name, then the bands needed for that style will be returned. e.g. for NDVI, red and NIR will be returned - not the derived NDVI value.
> WCS styles parameter

- datacube_wms/ogc.py
There are now separate routes for each supported service protocol:
/wms
/wmts
/wcs
These are in addition to the top-level accept-all-services route at /
> Implement separate per-protocol routes.

- datacube_wms/product_ranges.py
- datacube_wms/wms_layers.py
> Fixed bugs inserting new multiproduct ranges.

- datacube_wms/product_ranges.py
> Fix crs conversion bug.

- Dockerfile
- datacube_wms/ogc.py
- datacube_wms/utils.py
- datacube_wms/wms.py
- requirements-opencensus.txt
- requirements.txt
This PR adds the beginnings of some optional OpenCensus tracing which can be used to better understand how the app functions.
Shouldn't have significant impact if it is not enabled.
> Add optional OpenCensus tracing

- Dockerfile
- docker/auxiliary/index-k/assets/update_ranges.sh
Remove suffix and add cli for dea-proto
> Dea proto patch

- datacube_wms/data.py
- datacube_wms/wms_cfg_example.py
- datacube_wms/wms_layers.py
Adds PQ support to multi-products, as discussed in issue #107
> Multiproduct with pq

- datacube_wms/ogc.py
- datacube_wms/templates/wms_capabilities.xml
- datacube_wms/wms_cfg_example.py
- datacube_wms/wms_layers.py
Add support for Attribution, AuthorityURL, Identifier, DataURL and FeatureListURL elements in WMS GetCaps request.
Bonus feature: Fix version negotiation code to address issue #109
> Missing getcaps metadata

- datacube_wms/product_ranges.py
- datacube_wms/wms_layers.py
> Gracefully drop products with missing temporal range metadata.

- datacube_wms/templates/wms_capabilities.xml
- datacube_wms/wms_layers.py
Terria can't handle empty folders in WMS GetCaps
> Don't include empty platform groups

- Dockerfile
- update_ranges.py
> Fix default command to actually work

- README.rst
Added link to clone repository into the README and also updated commands required to get update_ranges.py to work when initialising and adding products.
> documentation updates to README.rst

- Dockerfile
Create an `owsuser` user within the docker file and run `OWS` docker image as an `owsuser` instead of root user.
> Run container as an owsuser

- Dockerfile
Reverts opendatacube/datacube-ows#131
> Revert "Run container as an owsuser"

- Dockerfile
- README.rst
- datacube_wms/data.py
- datacube_wms/ogc.py
> Call set_default_rio_config once only

- datacube_wms/data.py
Some obvious performance optimisations for GetFeatureInfo.  Yields maybe 10-20% improvement depending on data in local tests.
> Performance optimisations for GetFeatureInfo

- datacube_wms/data.py
Attempts to address Issue #147
> Use Fuse function in GetFeatureInfo. Intended to address Issue #147.

- datacube_wms/data.py
- datacube_wms/ogc_utils.py
- datacube_wms/product_ranges.py
Fix for Issue #149 (and some a couple of handy minor features backported from config_refactor)
> Getinfo nodata

- datacube_ows/feature_info_utils.py
Added function to be reused to fetch feature info's from CSV. This template can be followed for other configs fetching info from http(s) hosted CSV's.
> #173 Support external getfeatureinfo calls

- docs/usage.rst
Document layer deployment for new users.
> #166 Document deploying a layer via odc to ows

- .gitignore
- datacube_ows/band_mapper.py
- datacube_ows/ows_cfg_example.py
Attempt to fix mpl_ramp based legends alway having 0.0-1.0 as ticks.
> #172 Propose using offsets to correct legends

- docs/styles.rst
Start documenting styles outside of code and link to the code as the source of truth for latest work on styles.
> #176 start documenting styles

- datacube_ows/ows_configuration.py
Fix #179 by skipping over the null ranges layer and raising an exception.
> #179 Raise exception on Null ranges

- datacube_ows/ows_cfg_example.py
- datacube_ows/ows_configuration.py
- datacube_ows/templates/wcs_capabilities.xml
- datacube_ows/templates/wcs_desc_coverage.xml
- datacube_ows/templates/wms_capabilities.xml
- datacube_ows/templates/wmts_capabilities.xml
Will have some impact on GetCaps performance.  Use "dynamic" option sparingly.
> Support for "dynamic" products, where ranges are not cached in memory.

- datacube_ows/band_mapper.py
- datacube_ows/band_utils.py
- datacube_ows/data.py
- datacube_ows/ogc_utils.py
- datacube_ows/ows_cfg_example.py
- datacube_ows/ows_configuration.py
- datacube_ows/utils.py
- datacube_ows/wms_utils.py
- tests/test_band_mapper.py
- tests/test_data.py
This PR adds:
1) Support for "delta" styles, e.g. for presenting the difference in an index (e.g. NDVI) between two dates.
2) Support for per-band scaling.
3) Support for per-channel styling.  (e.g.  red, green, blue = NDBI, NDVI, NDWI)
> Style enhancements

- README.rst
I see you are migrating README instructions into folders, not sure if this aligns somewhere
> Add instruction on setting up new database

- docs/installation.rst
Don't know why they were this way.
> reST fixes

- docs/installation.rst
> python setup.py install

- Dockerfile
https://github.com/opendatacube/datacube-ows/issues/207
> Install postgres 11 client for ows

- requirements.txt
https://github.com/opendatacube/datacube-ows/issues/237
> Fix gevent issue

- datacube_ows/data.py
- datacube_ows/wms_utils.py
> Fix Feature Info Flag handling. (Especially for ignore_time case)

- datacube_ows/ows_cfg_example.py
- datacube_ows/templates/index.html
- datacube_ows/utils.py
- ows_test_cfg.py
- setup.py
Just a few opinionated changes :-)
> Change open datacube to open data cube and OGC to Open for consistency

- datacube_ows/data.py
> Fix ignore-time regression.

- requirements.txt
Most recent built with 2.5.0 is broken
> Fix pylint version to 2.4.4

- datacube_ows/data.py
- datacube_ows/ows_configuration.py
> Various fixes

- datacube_ows/wcs2.py
Collection of additional fixes for WCS 2 implementation.
Awaiting additional testing.
> Fixes for WCS 2 implementation

- tests/conftest.py
- tests/test_no_db_routes.py
- Run some tests using [Flask Test Client](https://flask.palletsprojects.com/en/1.1.x/testing/)
- Without any DB linked up these fail, but we exercise more code and get some coverage.
- There is also no OWS Config which causes further errors ( 5xx) , these tests may need to be updated for integration tests.
> #287 Quick hack to improve coverage

- check-code.sh
- tests/test_cfg_inclusion.py
- A bunch of replacement for permanent environment modification in tests with temp monkeypatches. Closes #293 .
> #293 some monkey patching

- datacube_ows/cube_pool.py
- datacube_ows/data.py
- datacube_ows/ogc.py
- datacube_ows/ows_configuration.py
- datacube_ows/wcs1_utils.py
- datacube_ows/wcs2_utils.py
> Cube pool was not handling database exceptions cleanly.

- .env
- .github/.codecov.yml
- integration_tests/conftest.py
- integration_tests/test_wcs_server.py
- integration_tests/test_wms_server.py
- integration_tests/test_wmts_server.py
- ows_test_cfg.py
- tests/test_ows_configuration.py
- Fix baseurl issue
- WMS (getmap, getfeatureinfo)
- WMTS (gettile)
Added manual generated URL to get the following:
- WCS (describecoverage, getcoverage)
- add test for legend generator
> Add manual/pattern generated queries

- requirements-dev.txt
New build of pycharm, new debug client.
Shouldn't effect anyone who isn't actively debugging.
> Update pycharm remote debug client version.

- datacube_ows/wms_utils.py
Urgent fix for bug affecting D61 delta testing.
This is unrelated to #330
> Fix GetLegendGraphic requests.

- datacube_ows/data.py
GetFeatureInfo bug - simple typo.
> Fix GetFeatureInfo bug

- tests/test_band_utils.py
- Create test XArray and Numpy arrays with ones
- Use band utils to process maths on them and increase test coverage using easy unit tests.
> #287 Start covering band utils

- datacube_ows/band_mapper.py
- datacube_ows/legend_generator.py
- datacube_ows/ows_cfg_example.py
- tests/test_legend_generator.py
Rewrite of colour ramp auto legends.  See Issue #328 for documention of new format.
Tests and cleanup needed before merge.
> Colourramp legend

- datacube_ows/band_mapper.py
Turns out it did break dev - see #348
> Fix code regression.  How did this not break dev?

- datacube_ows/band_mapper.py
I think what happened was I was halfway through refactoring component styles and accidentally jumped in the source file to the equivalent code for HybridStyles and ended up leaving component styles half unrefactored.
We need better test coverage of this code.
> Fix getmap component regression

- datacube_ows/band_mapper.py
And CI framework was allowing tests to fail, so nobody noticed.
> Hybrid Styles have been broken for a while.

- .env
- datacube_ows/ogc.py
- docker-compose.db.yaml
- docker-compose.yaml
- add Prometheus additional label to enable filter by service, request and layer
`sort_desc(flask_ows_request_full_url_sum{service="ows-ping-datacube-ows"})`
> Add new label for ows prometheus

- datacube_ows/wcs_scaler.py
- tests/test_wcs_scaler.py
Unit tests for `wcs2_scaler.py` as per #347.  Also fixes several corner case bugs I found during testing.
> Test wcs scaler

- integration_tests/test_wcs_server.py
> wcs20 netcdf integration test fix

- docs/index.rst
- docs/pyspy.rst
- add instruction to start up pyspy as docker-compose container
> Add pyspy instruction to ows doc

- datacube_ows/product_ranges.py
Fixes immediate issue in #310 Multi-products now behave the same as products for no data case.
(Baby steps towards testing of multiproducts)
> Multi-product merge was not failing cleanly when there's no data.

- .github/workflows/main.yml
- no need to run action if change is only to doc folder or README
> Add condition to github action

- datacube_ows/ows_configuration.py
Fix isues with warning logic in native resolution and CRS config loading identified by @pindge
> Fix native cfg issues

- README.rst
- docs/database.rst
- docs/index.rst
- docs/installation.rst
ODC schema?  Materialised Views??  Update_ranges???   
What does it all mean?
Undocuments the --blocking flag.
> Document OWS database for administrators.

- datacube_ows/product_ranges.py
updating ranges for one product over-writes the geolimits for all products.  :(
> Fix update ranges geolimits

- datacube_ows/sql/extent_views/create/018_grant.sql
Pulling this from the mv_search_redux branch coz we need it now.
> Mv permissions

- .github/.codecov.yml
- check-code-all.sh
- datacube_ows/product_ranges.py
- integration_tests/conftest.py
- integration_tests/test_update_ranges.py
- integration_tests/test_wms_server.py
- ows_test_cfg.py
Due to `update ranges` not failing and instead print out an error message, add output assertion to `update-ranges`
```
E           ERROR: OWS schema or extent materialised views appear to be missing 
E         ? +++++
E                   Try running with the --schema options first.
integration_tests/test_update_ranges.py:29: AssertionError
______________________________ test_update_ranges ______________________________
runner = <click.testing.CliRunner object at 0x7fe72003aac8>
def test_update_ranges(runner):
result = runner.invoke(main)
>       assert 'ERROR' not in result.output
E       AssertionError: assert 'ERROR' not in 'Deriving ex...ons first.\n'
E         'ERROR' is contained here:
E           _scene...
E           ERROR: OWS schema or extent materialised views appear to be …
```
> Assertion test for update ranges

- datacube_ows/band_utils.py
- datacube_ows/cube_pool.py
- datacube_ows/data.py
- datacube_ows/ows_configuration.py
- tests/test_band_utils.py
- tests/test_time_res_method.py
Trying to pull some refactorings out of a couple of more experimental branches in the name of digestible PRs.
> Cleanup refactors

- datacube_ows/ows_configuration.py
- datacube_ows/product_ranges.py
- datacube_ows/wcs1_utils.py
- datacube_ows/wcs2_utils.py
- datacube_ows/wcs_scaler.py
- datacube_ows/wms_utils.py
- integration_tests/test_wcs_server.py
- integration_tests/test_wms_server.py
- ows_test_cfg.py
- tests/test_wcs_scaler.py
> Crs aliases

- datacube_ows/ogc.py
- datacube_ows/ogc_utils.py
- datacube_ows/protocol_versions.py
- datacube_ows/startup_utils.py
- tests/test_startup.py
> Unsigned s3 access

- datacube_ows/data.py
- datacube_ows/ows_configuration.py
- docs/cfg_layers.rst
- ows_test_cfg.py
1) Bug in manual merge alpha channels fixed.
2) Bug in non-manual-merge solar-angle-correction fixed by making solar-angle-correction require manual-merge.
3) Deprecation warning when manual merge is used on a layer without solar angle correction.
> Solar correction fix

- datacube_ows/data.py
Fixing a nasty little bug in PR#406
> Mask handling for manual merge path was inverted.

- datacube_ows/styles/__init__.py
- datacube_ows/styles/base.py
- tests/test_multidate_handler.py
- tests/test_styles.py
- Test multi-date with lots of mocks
- Activate pq and other mask code paths.
- Remove untested exception handling code paths
Signed-off-by: Tisham Dhar <whatnickd@gmail.com>
> #410 test multi-date handler

- .github/.codecov.yml
> Increase threshold

- .github/workflows/scan.yml
- README.rst
Adds a GitHub status badge for Vulnerability scanning.
Fixes invalid branch reference in the Scan action
> Adds status badge and fixes scan action

- datacube_ows/data.py
Fix for #413.  Takes inspiration from #414 but doesn't try to treat open geometries as closed geometries.  Raises warnings for screwy data which might get annoying if a lot of data is screwy, but this  is a workaround for screwy data, not a bug fix.
> Fix geometry collection extents

- datacube_ows/styles/__init__.py
- datacube_ows/styles/base.py
- datacube_ows/styles/colormap.py
- datacube_ows/styles/component.py
- datacube_ows/styles/hybrid.py
- datacube_ows/styles/ramp.py
- tests/test_styles.py
Refactor and cleanup - required for #429
> Change the way Styles are constructed to be more extensible.

- README.rst
> Update status badge for correct CI

- .github/workflows/test.yml
- check-code.sh
Creates Isolated version of tests workflow.
> Add isolated test workflow #431

- .github/workflows/docker.yml
> #445 Short circuit redundant functional tests

- datacube_ows/band_utils.py
- datacube_ows/cfg_parser.py
- tests/test_band_utils.py
Required for https://github.com/digitalearthafrica/config/issues/93
> New band util function to handle radar vegetation index.

- datacube_ows/ows_cfg_example.py
- datacube_ows/ows_configuration.py
- datacube_ows/templates/wmts_capabilities.xml
- datacube_ows/tile_matrix_sets.py
- datacube_ows/wmts.py
- docs/cfg_global.rst
- docs/cfg_wmts.rst
- docs/configuration.rst
- integration_tests/test_wmts_server.py
- tests/test_cfg_tile_matrix_set.py
Merge DEA-Config PR https://github.com/GeoscienceAustralia/dea-config/pull/614  first, or support for VicGrid Tile Matrix Set will disappear.
> Configurable Tile Matrix Sets

- .github/workflows/scan.yml
> #460 replace set-env with logging tag to file

- wms_xsds/capabilities_extensions.xsd
Draft XSD document for WMS extensions.  No implementation yet - just the XSD.
> WMS Extensions XSD.

- datacube_ows/ogc.py
> Catch WMSException in legend method.

- datacube_ows/sql/extent_views/create/011_create_new_space_view_raw.sql
Responding to user request.
Run `python update_ranges.py --schema --role myrole` to install - only required if you intend to make use of the 'boku' metadata type.
> Add boku metadata type for @jankovicgd  (See #415)

- datacube_ows/data.py
Include the matching ODC dataset IDs for the query in ows_stats output.
Should help with #474.
> Show selected dataset IDS in ows_stats output.

- datacube_ows/band_utils.py
- docs/cfg_functions.rst
- docs/cfg_wcs.rst
Fix errors and omissions in documentation, as spotted during TGIF.
> Documentation tweaks

- Dockerfile
- requirements-dev.txt
Only affects developers who debug with pycharm.
> Update pydevd version for Pycharm 2020.3

- datacube_ows/wcs2_utils.py
- integration_tests/test_wcs_server.py
- tests/test_wcs2_utils.py
Backfilling WCS1 and 2 coverage gaps, mostly WCS2.
Also a handful of minor bugfixes found during testing - Seems like a good point to merge this PR and start a new one.
> More wcs tests

- datacube_ows/wcs1.py
- datacube_ows/wcs1_utils.py
- integration_tests/test_wcs_server.py
- integration_tests/utils.py
Bumping that coverage number a little bit higher before Christmas.
> WCS1 basic tests and desc coverage tests.

- docs/cfg_colourmap_styles.rst
- docs/cfg_colourramp_styles.rst
- docs/cfg_component_styles.rst
- docs/cfg_functions.rst
- docs/cfg_global.rst
- docs/cfg_hybrid_styles.rst
- docs/cfg_layers.rst
- docs/cfg_styling.rst
- docs/cfg_wcs.rst
- docs/cfg_wms.rst
- docs/cfg_wmts.rst
- docs/configuration.rst
- integration_tests/test_wcs_server.py
- requirements.txt
- fix test `owslib` has been updated and `WCS` no longer supports `timeout`
- impossible to find the section without expanding all.
- add more info to section heading
- make `cfg_*_styles` actually list on the side.
> add clarity to doc and fix test

- integration_tests/conftest.py
- integration_tests/test_cfg_parser.py
- integration_tests/test_layers.py
- integration_tests/test_mv_index.py
- integration_tests/test_routes.py
- integration_tests/test_update_ranges.py
- integration_tests/test_wcs_server.py
- integration_tests/test_wms_server.py
- integration_tests/test_wmts_server.py
- integration_tests/utils.py
- requirements.txt
- pin `owslib` to `0.21.0` as `0.22.0` is broken upstream
- apply black formatting'
- remove unused imports
> fix integration test

- datacube_ows/cfg_parser.py
change cfg to exit if mismatch
> exit on diff

- datacube_ows/templates/wms_capabilities.xml
Addresses #503 
(Thanks to @mvaaltola on github for noticing and raising an issue)
> Restored CRS GetCaps entries - MIA since late 2019.

- datacube_ows/templates/wms_capabilities.xml
- integration_tests/test_wms_server.py
- wms_xsds/capabilities_1_3_0.xsd
Draft PR working on full WMS XSD compliance.  See #508 
- unlimit `layer` 
- enable wms getcap` XML parsing
> Wms xsd compliance

- datacube_ows/config_utils.py
- datacube_ows/data.py
- datacube_ows/ows_configuration.py
- datacube_ows/styles/base.py
- datacube_ows/wcs1_utils.py
- datacube_ows/wcs2_utils.py
Previous PR broke GetFeatureInfo requests.
> Handle all flag-prodcut-bands for GetFeatureInfo requests.

- datacube_ows/startup_utils.py
instead of creating alot of projects, we will config environment 
https://docs.sentry.io/platforms/python/configuration/environments/
> add sentry env support

- datacube_ows/data.py
Quick fix for Dave's bug.  Needs better unit tests.
> GetFeatureInfo was breaking on flags with no description.

- datacube_ows/__init__.py
- tests/test_styles.py
> Update default version number, ready for 1.8.3 tag/release.

- docs/cfg_styling.rst
This is at least my fourth attempt to document how `pq_masks` works in way which isn't hopelessly confusing.  
Have I finally made everything clear?  Have I just made it even more confusing??  I can't tell any more.  Help!
> Clarify pq_mask logic.  (Or have I just made it more confusing.)

- README.rst
- docs/cfg_colourmap_styles.rst
- docs/cfg_colourramp_styles.rst
- docs/cfg_component_styles.rst
- docs/cfg_functions.rst
- docs/cfg_layers.rst
- docs/cfg_styling.rst
- docs/cfg_wcs.rst
- docs/cfg_wmts.rst
- docs/configuration.rst
- docs/database.rst
Mostly fixing broken internal links.
> Doc cleanup

- ows_test_cfg.py
- remove faulty styles ( reduce space)
- update `flags` and `pq_masks` to be a list as of the latest change 
- update wofs style to use the latest wofs style changes
> cleanup ows test cfg

- .github/workflows/lint.yml
- datacube_ows/product_ranges.py
- datacube_ows/styles/__init__.py
- datacube_ows/styles/api.py
- datacube_ows/styles/colormap.py
- datacube_ows/utils.py
- datacube_ows/wcs1_utils.py
- datacube_ows/wcs2.py
- datacube_ows/wcs2_utils.py
- datacube_ows/wcs_scaler.py
- datacube_ows/wcs_utils.py
- datacube_ows/wms_utils.py
- datacube_ows/wmts.py
- tests/test_cfg_cache_ctrl.py
- tests/test_cfg_global.py
- tests/test_cfg_inclusion.py
- tests/test_cfg_metadata_types.py
- tests/test_data.py
- tests/test_legend_generator.py
- tests/test_no_db_routes.py
- tests/test_ogc_utils.py
- tests/test_ows_configuration.py
- tests/test_startup.py
- tests/test_time_res_method.py
- tests/test_wcs_scaler.py
- add `# noqa: F401` to pass flake8
- remove imported but unused
> remove imported but unused

- datacube_ows/ogc_utils.py
- datacube_ows/styles/api/__init__.py
- datacube_ows/styles/component.py
- docs/style_howto_components.rst
- docs/style_howto_components_nonlinear.rst
- docs/style_howto_transparency.html
Includes some bug fixes to "standalone styles" found while writing examples.
I like to merge these documentation patches pretty regularly because I like to be able to preview them on readthedocs.
> Howto for nonlinear components styles

- HISTORY.rst
- README.rst
- datacube_ows/__init__.py
- setup.py
* Increment version number
* Update history file.
* Cleanup of setup.py to clear pypi hurdles.
> Ready for 1.8.5 release

- datacube_ows/styles/base.py
> Attempted fix for DEAfrica EMAD issue.

- docs/style_howto_color_map.rst
- docs/style_howto_color_ramp.rst
- docs/style_howto_components.rst
- docs/style_howto_components_nonlinear.rst
- docs/style_howto_legends.rst
- docs/style_howto_transparency.rst
- docs/styling_howto.rst
The basic things you don't notice until they get rendered by readthedocs.
> Howto corrections

- datacube_ows/data.py
As reported by @GypsyBojangles 
Affected queries where the masking product returns data but the main product does not.  (E.g. When masking a multi-date landsat product against a single-time product like coastlands).
> Multiproduct masking bugfix.

- .github/workflows/lint.yml
- Dockerfile
* Restore necessary whitespace in Dockerfile
* Tell flake8 to ignore Dockerfile.
> Fix pycharm in Dockerfile.

- docs/style_howto_color_map.rst
- docs/style_howto_color_ramp.rst
- docs/style_howto_components.rst
- docs/style_howto_components_nonlinear.rst
- docs/style_howto_transparency.rst
- docs/styling_howto.rst
> More Howto corrections

- datacube_ows/__init__.py
- docs/style_howto_color_map.rst
- docs/style_howto_color_ramp.rst
- docs/style_howto_components.rst
- docs/style_howto_components_nonlinear.rst
- docs/style_howto_transparency.rst
- docs/styling_howto.rst
Increment default version number.
> For rel 1.8.6

- datacube_ows/data.py
Problem is the xarray assign function seems to change integer bands to floats.  This should work better.
> Fix multiprod masking issue

- .github/workflows/pypi.yml
- keep to release only
- push to actual pypi
> Fix pypi version

- tests/conftest.py
- tests/test_style_api.py
Testing the style engine more systematically.
> Style testing

- datacube_ows/data.py
- datacube_ows/ows_cfg_example.py
- datacube_ows/styles/base.py
- docs/cfg_styling.rst
- tests/test_data.py
Addresses #548.
Now with increased test coverage.
> Multidate ordering

- datacube_ows/ogc_utils.py
- datacube_ows/ows_cfg_example.py
- datacube_ows/ows_configuration.py
- docs/cfg_layers.rst
- tests/test_ogc_utils.py
- tests/test_time_res_method.py
Support for daily time resolution with summary-style time coordinates (as opposed to local solar-date style time coordinates).  Requested by @valpesendorfer
> Daily data nonlocal dates

- Dockerfile
- constraints.txt
- datacube_ows/ogc.py
First minimal attempt.  Seems to work for me, seeing how Github actions cope.  :)
> Move to Python3.8 geobase.

- .env_ows_root
- .env_simple
- docker-compose.yaml
- update sample env and docker-compose file for ows_root_config.py to be mounted correctly and work
> update sample env file

- docs/configuration.rst
Some minor corrections for the recently changed `configuration.rst` documentation. 
Details in the comments
> Minor corrections for `configuration.rst` docs

- MANIFEST.in
- setup.py
dont build `tests` and `integration_tests` folders into python lib
> ignore test

- Dockerfile
- docker/database/Dockerfile
- move `pip install` together
- install postgres client version 12
- use `postgis` 12.4 image
> optimize dockerfile

- Dockerfile
- requirements.txt
- test.sh
merge `apt-get install` together
declare PY_PATH before using it
> merge apt-get

- .github/workflows/docker.yml
- .github/workflows/dockerfile-lint.yml
- .github/workflows/lint.yml
- .github/workflows/test.yml
- Dockerfile
- datacube_ows/cfg_parser.py
- update workflow names to correctly reflect their purpose
- add dockerfile lint workflow
- - ignore ```Error: Dockerfile:42 DL3008 warning: Pin versions in apt get install. Instead of `apt-get install <package>` use `apt-get install <package>=<version>```
- add more restriction to workflow trigger condition
- update Dockerfile as per hadolint recommendation
```
Error: Dockerfile:20 DL3020 error: Use COPY instead of ADD for files and folders
Error: Dockerfile:22 SC2006 style: Use $(...) notation instead of legacy backticked `...`.
Error: Dockerfile:23 DL3042 warning: Avoid use of cache directory with pip. Use `pip install --no-cache-dir <package>`
Error: Dockerfile:23 DL3059 info: Multiple consecutive `RUN` instructions. Consider consolidation.
Error: Dockerfile:28 DL3042 warning: Avoid …
```
> add dockerfile-lint

- docs/style_howto_transparency.rst
- docs/styling_howto.rst
- docs/styling_howto_jupyter.rst
Fixing for style workshops starting tomorrow.
> Some documentation typos and clarification.

- docs/configuration.rst
- docs/style_howto_color_ramp.rst
- docs/style_howto_components.rst
- docs/style_howto_components_nonlinear.rst
- docs/style_howto_transparency.rst
* Fix typos from recent PRs.
* Fix HOWTO typos and omissions found during first workshop.
> Documentation updates

- datacube_ows/data.py
> Second attempt to implement solution 2.

- docs/conf.py
- docs/usage.rst
This works nicely locally, need to merge to master to test on readthedocs!
> Autodocument CLI tools from man pages.

- datacube_ows/ows_configuration.py
- datacube_ows/update_ranges.py
Suppress null range errors when running update_ranges on a new layers for the first time.
Addresses #615.
> Suppress suprious error messages in update_ranges

- docs/requirements.txt
Oops, hadn't added `docs/requirements.txt` to git.
> Attempt to fix broken readthedocs build.

- datacube_ows/data.py
This fixes the error observed in DEA Fractional Cover.
> Multi-product-masking bug fix fix.

- docs/requirements.txt
- docs/usage.rst
- requirements-dev.txt
Also wordings more consistent in usage.rst
> Fix readthedocs click-integration. 

- datacube_ows/config_utils.py
More helpful error message on a particular mask config error condition.
> Give helpful error message on missing flags_definition.

- docs/cfg_colourramp_styles.rst
> Color/colour confusion fixed.

- datacube_ows/__init__.py
> Increment version number for 1.8.11 release.

- docs/styling_howto.rst
- docs/styling_howto_jupyter.rst
Mostly around style API and JupyterHub use.
For ODC conference workshops.
> Documentation updates.

- datacube_ows/ows_configuration.py
- datacube_ows/templates/wms_capabilities.xml
- datacube_ows/wcs2.py
- datacube_ows/wms_utils.py
- docs/cfg_layers.rst
- integration_tests/cfg/ows_test_cfg.py
- integration_tests/test_wcs_server.py
- tests/test_cfg_layer.py
- tests/test_wms_utils.py
Addresses #512
Regular time dimension support for protocols that support it (WMS, WCS2)
> Regular time dimensions

- datacube_ows/wcs2_utils.py
> Attempted fix for WCS2 band alias bug.

- datacube_ows/data.py
- dive-ci.yml
> Return an empty response if data for any of requested dates is not available

- datacube_ows/ogc_utils.py
- tests/test_ogc_utils.py
- tests/test_time_res_method.py
Due to poor timezone handling.
> summary products (time_resolution not "raw") were broken in Africa

- datacube_ows/ogc_utils.py
- datacube_ows/utils.py
- tests/test_ogc_utils.py
- tests/test_ows_configuration.py
- tests/utils.py
Cleaning up messy and redundant code.
Closing test coverage.
Adding docstrings.
Type hints.
Starting with some low-level utility files.
> Cleanup refactor

- .github/workflows/dive.yml
> use latest docker lint

- datacube_ows/cube_pool.py
- datacube_ows/mv_index.py
- integration_tests/test_mv_index.py
More cleanup and test coverage.
> Cleanup of mv_index.  (Also Fix type hints in cube_pool)

- datacube_ows/config_utils.py
- datacube_ows/ows_configuration.py
- datacube_ows/styles/base.py
- tests/test_ows_configuration.py
- tests/test_styles.py
styles/base.py - cleanup, docstrings and type hints.
The architectural changes needed to properly support animations have been marked with TODOs.
> Style base clean up

- .pre-commit-config.yaml
- lint-code.sh
- requirements-dev.txt
> #667 First cut of pre-commit

- datacube_ows/data.py
- datacube_ows/ogc_utils.py
- datacube_ows/styles/base.py
- datacube_ows/styles/ramp.py
- docs/cfg_colourramp_styles.rst
- docs/cfg_styling.rst
- tests/test_multidate_handler.py
- tests/test_ogc_utils.py
Time aware masking in time-series animations, and support for time-series animations for all style types.
Biggest obstacles to time-series animations being ready for production are resource-limit management and client support.
Small change this might break something, so please don't merge until Pin has run up a test cluster.
> Style API refactor for better multidate support - especially animations

- datacube_ows/product_ranges.py
* This is opinionated, but I think a lack of datasets is not an error. Let's call it a warning!
> I think this is a warning, not an error.

- HISTORY.rst
- datacube_ows/__init__.py
Increment default version number and update history.rst.
> Ready for 1.8.15

- datacube_ows/data.py
- datacube_ows/ows_configuration.py
- datacube_ows/resource_limits.py
- datacube_ows/styles/base.py
- datacube_ows/wcs1.py
- datacube_ows/wcs1_utils.py
- datacube_ows/wcs2_utils.py
- integration_tests/test_update_ranges.py
- integration_tests/test_wms_server.py
- tests/test_cfg_cache_ctrl.py
- tests/test_cfg_layer.py
- tests/test_style_api.py
Cleanup resource limit code, and separate into it's own module.  Not so much addressing #680 as making it more addressable.
> Resource limit refactor

- datacube_ows/data.py
- datacube_ows/resource_limits.py
- datacube_ows/styles/base.py
- datacube_ows/tile_matrix_sets.py
- datacube_ows/wms_utils.py
- datacube_ows/wmts.py
- docs/cfg_layers.rst
- tests/test_cfg_layer.py
- tests/test_resource_limits.py
- tests/test_wcs_scaler.py
See documentation changes.
Note slight backwards compatibility issue - the default behaviour if no resource limits are set has changed.  New behaviour (no limits) is more consistent and general.
> Resource mgmt

- datacube_ows/config_utils.py
- datacube_ows/ogc_utils.py
- datacube_ows/ows_configuration.py
- tests/cfg/broken_nested.py
- tests/test_cfg_inclusion.py
- tests/test_cfg_layer.py
- tests/test_ows_configuration.py
Better reporting of certain config error cases that are easy to make accidentally.  
Also addresses what's left of #487
> Config tweaks

- datacube_ows/__init__.py
> Increment default version number

- datacube_ows/data.py
- datacube_ows/ogc.py
- datacube_ows/startup_utils.py
- tests/test_startup.py
Addresses #694.  Replaces #697.  Identical to #697 but with a less tangled commit history.
> Renewable S3 credentials - fixed squash of tangled git history.

- datacube_ows/config_utils.py
> Direct inheritance of objects where named inheritance can also apply was broken

- tests/test_startup.py
Fix coverage gaps from dynamic credential PR.
> Startup test coverage

- datacube_ows/ogc_exceptions.py
- datacube_ows/wmts.py
- integration_tests/test_wmts_server.py
More bug fixes too!  Nothing as major as yesterday's though.
> More WMTS tests.

- .github/workflows/lint.yml
- lint-code.sh
- remove lint-code.sh
- setup pylint as github workflow jobs in lint workflow
- this reduces lint workflow completion time from 6-7ms to 2-3ms
> replace lint-code inside docker container with native github action job

- datacube_ows/styles/ramp.py
> Fix numpy.typing import weirdness

- datacube_ows/resource_limits.py
- datacube_ows/wcs1.py
- datacube_ows/wcs1_utils.py
- datacube_ows/wcs2.py
- datacube_ows/wcs2_utils.py
- datacube_ows/wmts.py
- integration_tests/test_wcs_server.py
- integration_tests/test_wmts_server.py
Add ows_stats performance tool to WMTS and WCS.
> Ows stats all protocols

- setup.py
Should probably do it here too.
> Mirror s3fs version pinning from requirements.txt in setup.py

- check-code-all.sh
- datacube_ows/styles/ramp.py
- docs/cfg_style_api.rst
Found some bugs in the legend generator while writing the HOWTO.
> Bug fixes in the legend generator

- docs/cfg_colourramp_styles.rst
- docs/style_howto_legends.rst
Last chapter of HOWTO.  Let's merge so we can see how it looks on the readthedocs, and apply any urgent fixes before the next release.
> Howto for autolegends

- HISTORY.rst
- datacube_ows/__init__.py
Update default version to 1.8.22+
Added new and historic release notes to HISTORY.rst
> Update default version and release notes

- datacube_ows/data.py
- tests/test_data.py
Fill missing flag data with band nodata value instead of zero.  Addresses #768.
> Fill missing flag data with band nodata value instead of zero.

- datacube_ows/ogc.py
- datacube_ows/startup_utils.py
NB: This PR breaks Codecov's coverage comparison algorithm, so I think we'll just have to wear the slight drop in coverage.
> Significant overhaul of Prometheus metrics for better monitoring.

- HISTORY.rst
- datacube_ows/ogc.py
One last tweak to Prometheus metrics.
> Upgrade OGC metrics to histogram. Update History.rst.

- HISTORY.rst
- datacube_ows/__init__.py
Increment default version number and update HISTORY.rst ready for release 1.8.24
> For 1.8.24

- datacube_ows/legend_generator.py
There seem to be some strange flask/prometheus interactions happening. This might (? probably won't) fix it?
> Make legend view return a tuple.

- .github/workflows/test-prod.yaml
- tests/test_cfg_global.py
- fix prod docker-compose workflow
- add internationalised cfg test
> setup internationalised unit test

- datacube_ows/styles/colormap.py
Significant rewrite of the colour-map (aka value_map) style rendering algorithm.
A lot of redundant conversions and mask manipulations have been removed, but the biggest performance win comes from simply jumping to the next rule as soon as it is clear that the current rule matches no pixels in the current tile.  This significantly improves performance when:
1) There are a lot of rules defined, and
2) Only a relatively small proportion are represented in any given tile.
Performance of colour map styles only becomes an issue when condition 1 holds.
The performance bottleneck is now  the `xarray.where()` function (to the extent that there is no point in looking for performance optimisations elsewhere).   This function is called once per rule that matches at least one pixel in the tile, which …
> Improve efficiency of colour-map style rendering algorithm.

- HISTORY.rst
- datacube_ows/__init__.py
Increment default version number and update HISTORY.rst
> Increment default version number.

- README.rst
- datacube_ows/startup_utils.py
the current log contains the following 
```
{"log":"[2022-03-15 05:59:21,633] root [0e387423-5fec-42ea-ba55-4f6600397fe0] [INFO] request: http://10.95.73.12:8000/?srs=EPSG%3A3857\u0026transparent=true\u0026format=image%2Fpng\u0026exceptions=application%2Fvnd.ogc.se_xml\u0026styles=\u0026tiled=true\u0026feature_count=101\u0026service=WMS\u0026version=1.1.1\u0026request=GetMap\u0026layers=aster_false_colour\u0026bbox=14088873.053523686%2C-1878516.4071364924%2C14401959.121379767%2C-1565430.3392804079\u0026width=256\u0026height=256 returned status: 200 and took: 61 ms ","stream":"stderr"}
```
which is linked to https://github.com/opendatacube/datacube-ows/blob/964f86e0c6adbcd42e34aec79fc1cb52ed75d484/datacube_ows/startup_utils.py#L43 
the `(name) and `request_id` has limited value, replacing …
> update logging to include ip

- Dockerfile
add translation to docker image
resolves #813
> fix datacube-ows-cfg babel tool

- CONTRIBUTING.rst
- docker-compose.db.yaml
- docker-compose.index.yaml
add instruction on how to build on top of existing db dump
> expand doc and add docker-compose.index.yaml

- HISTORY.rst
- datacube_ows/__init__.py
Update HISTORY.rst and default version number for release 1.8.28.
> For 1.8.28

- setup.py
Increase minimum datacube-core version to latest release.
> Increase minimum version of datacube-core.

- datacube_ows/utils.py
> Fix for dataset sorting in multi-product layers with multi-product masking

- README.rst
- add instruction to create ows environment with repository example config with conda
- allow consistency in installation procedures for issues such as #845
> add instruction to build ows environment with conda

- datacube_ows/startup_utils.py
so applications only using the styling API do not have excess dependencies.
> Isolate ops imports 

- HISTORY.rst
- datacube_ows/__init__.py
Update HISTORY.rst and default version string for 1.8.29 release.
> For release 1.8.29

- .github/workflows/test.yml
- simplify step names
- update codcov
- rearrange path condition so it triggers
v1 deprecated https://github.com/codecov/codecov-action
> upgrade codcov action to v3

- README.rst
- datacube_ows/startup_utils.py
- docs/environment_variables.rst
- tests/test_startup.py
fixes #867 
NOTE: Changes the interpretation of environment variables for Sentry.
> free up sentry to use any hosted sentry service

- .github/workflows/complementary-config-test.yaml
- .github/workflows/lint.yml
- .github/workflows/test-prod.yaml
- .github/workflows/test.yml
- docker-compose.db.yaml
- docker-compose.index.yaml
- docker-compose.yaml
- fixes #863 
- cleanup workflow files
fixes 
```
Valid connection:       Error Connecting to Database: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution
(Background on this error at: https://sqlalche.me/e/14/e3q8)
```
> cleanup docker-compose and workflow file

- .github/workflows/complementary-config-test.yaml
- check-code-all.sh
- complementary_config_test/.env_complementary_config_dea_dev
- docker-compose.cleandb.yaml
- integration_tests/test_wcs_server.py
- integration_tests/test_wms_server.py
> fix index for  getcaps

- datacube_ows/ows_configuration.py
- docker-compose.yaml
Some minor changes to better support trouble-shooting and local deployments.
> Debug tweaks

- HISTORY.rst
- README.rst
- datacube_ows/__init__.py
Updates to HISTORY.rst and README.rst, and default version string, ready for 1.8.30 release.
> Ready for 1.8.30 release

- datacube_ows/data.py
- datacube_ows/ows_configuration.py
- docs/cfg_layers.rst
- integration_tests/cfg/ows_test_cfg.py
- integration_tests/utils.py
Implement per-layer url_patch configuration (passed through to dc.load_data).
> Implement url_patch for layers.

- check-code-all.sh
- datacube_ows/data.py
- datacube_ows/templates/html_feature_info.html
- datacube_ows/templates/wms_capabilities.xml
- datacube_ows/wms_utils.py
- integration_tests/test_wms_server.py
We think offering HTML format for WMS/WMTS GetFeatureInfo *may* improve interoperability with ArcGIS.
Closes #882
> Getfeatureinfo html

- CONTRIBUTING.rst
----
:books: Documentation preview :books:: https://datacube-ows--904.org.readthedocs.build/en/904/
> fix schema typo

- datacube_ows/ows_configuration.py
- integration_tests/cfg/ows_test_cfg.py
- tests/conftest.py
- tests/test_cfg_layer.py
- tests/test_cfg_wcs.py
Grid counts for WCS are not being calculated correctly.
----
:books: Documentation preview :books:: https://datacube-ows--902.org.readthedocs.build/en/902/
> Fix grid counts.

- .github/workflows/docker.yml
----
:books: Documentation preview :books:: https://datacube-ows--908.org.readthedocs.build/en/908/
> convert + to underscore

- docs/styling_howto.rst
- add note re `group_by`
----
:books: Documentation preview :books:: https://datacube-ows--912.org.readthedocs.build/en/912/
> change jupyter readme to c3 product

- .github/workflows/doc-qa.yaml
- .github/workflows/docpreview.yaml
- .github/workflows/pyspellcheck.yaml
- docs/performance.rst
- spellcheck.yaml
- split pyspellcheck and documentatation preview to different workflows
- add rst to pyspellcheck
> spellcheck rst

- datacube_ows/product_ranges.py
- setup.py
Having some production problems in ows-update.  Adding some more progress messages to try and nut out what's happening.
----
:books: Documentation preview :books:: https://datacube-ows--942.org.readthedocs.build/en/942/
> Improve error condition reporting in ows-update.

- .pre-commit-config.yaml
- datacube_ows/ogc.py
- datacube_ows/startup_utils.py
- setup.py
- tests/test_startup.py
Applied failed CI autoupdates.
Update pins.
Update to new Flask-Babel API
Suppress SQLAlchemy warnings.
----
:books: Documentation preview :books:: https://datacube-ows--949.org.readthedocs.build/en/949/
> Repo maintenance

- Dockerfile
Local reproduction of @pjonsson's PR#960 to see if the github checks pass on a local branch.
----
:books: Documentation preview :books:: https://datacube-ows--970.org.readthedocs.build/en/970/
> Local reproduction of @pjonsson's PR#960

- .github/workflows/complementary-config-test.yaml
- .github/workflows/dive.yml
- .github/workflows/docker.yml
- .github/workflows/dockerfile-lint.yml
- .github/workflows/lint.yml
- .github/workflows/pypi.yml
- .github/workflows/pyspy-profiling.yaml
- .github/workflows/scan.yml
- .github/workflows/spellcheck.yaml
- .github/workflows/test-prod.yaml
- .github/workflows/test.yml
----
:books: Documentation preview :books:: https://datacube-ows--971.org.readthedocs.build/en/971/
> Consolidation of revent dependabot PRs.

- setup.py
> Update to OWSLib 0.29.3

- .github/workflows/docpreview.yaml
Update the doc preview config to match the documentation for the action, this hopefully removes the failure when merging to master.
> CI: update doc preview config

- .github/workflows/pypi.yml
----
📚 Documentation preview 📚: https://datacube-ows--994.org.readthedocs.build/en/994/
> Upgrade pypi publish action to supported version.

- pyproject.toml
- setup.py
This fixes a number of security issues.
----
📚 Documentation preview 📚: https://datacube-ows--1004.org.readthedocs.build/en/1004/
> Update Pillow, setuptools and wheel versions

- datacube_ows/update_ranges_impl.py
Closes #1010
Tested manually against local stale DB.
----
📚 Documentation preview 📚: https://datacube-ows--1016.org.readthedocs.build/en/1016/
> Add friendlier message for creating extents without updated views

- HISTORY.rst
- datacube_ows/__init__.py
- datacube_ows/update_ranges_impl.py
- tests/test_data.py
Cherry pick PRs #1013 and #1016 into develop-1.9
----
📚 Documentation preview 📚: https://datacube-ows--1018.org.readthedocs.build/en/1018/
> Develop 1.9 cherry picks

- .github/ISSUE_TEMPLATE/ISSUE_TEMPLATE.md
- datacube_ows/templates/wms_capabilities.xml
- datacube_ows/wcs1_utils.py
- datacube_ows/wcs_scaler.py
- integration_tests/test_wcs_server.py
- setup.py
Some minor bugfixes and tweaks, mostly around WCS.
Definitely addresses:
* Correctly apply default subsetting when the subsetting and output CRS are the same.  (Closes #1024)
* Corrects some typos in the issue template (as reported in #1026)
* Correctly generate nodata GeoTIFFS from WCS1 (Closes #1014)
Pretty sure it will also address:
* Handle a product disappearing from the database slightly more gracefully (hopefully addresses #1023)
But testing that last one is almost impossible with the current test framework.
----
📚 Documentation preview 📚: https://datacube-ows--1027.org.readthedocs.build/en/1027/
> WCS fixes.

- datacube_ows/data.py
- datacube_ows/ogc_utils.py
- datacube_ows/templates/wms_capabilities.xml
- datacube_ows/utils.py
- datacube_ows/wcs1_utils.py
- docs/cfg_styling.rst
- tests/test_ogc_utils.py
Backports of fixes in 1.9
* Fixes: #1038
* Fix other issues from upstream libraries
And a little bit of misc cleanup.
> Miscellaneous cleanup

- .github/workflows/complementary-config-test.yaml
- .github/workflows/pyspy-profiling.yaml
- .github/workflows/test-prod.yaml
- .github/workflows/test.yml
- datacube_ows/styles/colormap.py
- datacube_ows/styles/component.py
- datacube_ows/utils.py
- datacube_ows/wcs1_utils.py
- docker-compose.cleandb.yaml
- docker-compose.db.yaml
- docker-compose.prod.yaml
- docker-compose.pyspy.yaml
- docker-compose.yaml
- integration_tests/test_wcs_server.py
- tests/test_data.py
- tests/test_styles.py
- tests/utils.py
Fixes #1038 (hopefully properly) and suppresses several other warning messages coming from upstream API changes.
Also get docker-compose GHA's running without namespace collisions with 1.9 docker images.
----
📚 Documentation preview 📚: https://datacube-ows--1045.org.readthedocs.build/en/1045/
> Suppress various upstream warning messages.

- docker/pyspy/Dockerfile
This is the same version that the main
container currently uses.
----
📚 Documentation preview 📚: https://datacube-ows--1050.org.readthedocs.build/en/1050/
> pyspy: update to Python 3.10

- docker/pyspy/Dockerfile
This is the same version that the main
container currently uses.
----
📚 Documentation preview 📚: https://datacube-ows--1055.org.readthedocs.build/en/1055/
> pyspy: update to Python 3.12

- .github/workflows/complementary-config-test.yaml
- .github/workflows/lint.yml
- .github/workflows/pyspy-profiling.yaml
- .github/workflows/test-prod.yaml
- .github/workflows/test.yml
- Dockerfile
- docker/files/remap-user.sh
----
📚 Documentation preview 📚: https://datacube-ows--1067.org.readthedocs.build/en/1067/
> Fixups for #1065

- HISTORY.rst
- datacube_ows/__init__.py
Ready for 1.8 43 release
----
📚 Documentation preview 📚: https://datacube-ows--1089.org.readthedocs.build/en/1089/
> For 1.8.43
