opendatacube/datacube-ows

datacube_wms/product_ranges.py
Update ranges should now work correctly if datasets are archived and dates no longer have any valid datasets associated with them.
=> Update ranges handles different sized lists for dates

datacube_wms/ogc_utils.py, datacube_wms/templates/wcs_desc_coverage.xml, datacube_wms/wms_layers.py
Some products do not have a native CRS that is valid across all datasets, for example the current Sentinel 2 NRT GeoTiffs are stored using the UTM projections which will differ depending on location.
This PR will remove the DescribeCapabilities elements that use the Native CRS, however they are optional according to the WCS 1.0 spec
=> Support products with no Native CRS

docker/auxiliary/setup/Dockerfile, docker/auxiliary/setup/assets/create-db.tf
This enables the ability to create a database without relying AWS parameter store.
=> Add extra terraform script to enable deployment without param store

docker/auxiliary/index/Dockerfile
Newest datacube version removes scripts that were required for index.
=> Lock index to datacube version 0.2.8

datacube_wms/ogc.py, datacube_wms/ogc_utils.py, datacube_wms/wcs.py, datacube_wms/wms.py, tests/test_ogc_utils.py
Using the Host Header is useful for WMS deployments behind reverse proxies such as nginx.
=> Support Host header in determining base url

datacube_wms/legend_generator.py, datacube_wms/ogc.py, datacube_wms/templates/wms_capabilities.xml
By serving single-style legends from a set url and advertising it in the style section of the GetCapabilities document, we can just get a legend for the currently selected style (where that makes sense).  (Terria uses this method in preference to GetLegendGraphic if used in the GetCaps).
This seems to mostly work - there are a few code-branches in the legend code that look broken and presumably never get called.  Also, only a couple of band-mapping classes actually support legends currently.
=> Style-level legends.

requirements.txt
maybe fix `dea-proto` install
Newer version of `dea-proto` has `aiobotocore` as a non-optional dependency, but `aiobotocore` can not catch up with constant change in `botocore` library, so it has a limited range of supported versions. Installing it with feature flag `[awscli]` forces installation of compatible `boto3` lib.
=> Forcing aiobotocore installation with compatible boto3

datacube_wms/band_mapper.py, datacube_wms/data.py, datacube_wms/wms_cfg_example.py, datacube_wms/wms_layers.py
This PR is required to have a masking layer independent from the data.
It adds the options:
`pq_fuse_func`
`pq_ignore_time`
If not set, existing behaviour is maintained
=> Add masking options

datacube_wms/product_ranges.py, datacube_wms/templates/wcs_desc_coverage.xml, datacube_wms/wcs_utils.py, datacube_wms/wms_cfg_example.py, datacube_wms/wms_layers.py
WCS now works with ESRI Arcmap.
1. The actual storage CRS is always used as the native CRS if it exists. If it doesn't, the WCS native resolution can be specified in configuration.  If possible the native CRS should be as close to equal area over the region covered.  (GDA94/EPSG:3577 is an excellent choice for Australia!)
2. WCS servers must now explicitly declare their resolution in the native CRS.
3. The rectified grid is calculated from the bounding box and the configured native resolution - this is MUCH faster than the previous method.
4. Various bug fixes.
There are a couple of undocumented configuration items that have been useful for testing.  I am leaving them in place for now, but they may be removed without notice at a later date.
=> Arcmap-compatible WCS support

datacube_wms/band_mapper.py, datacube_wms/band_utils.py, datacube_wms/wms_cfg.py, datacube_wms/wms_cfg_example.py, tests/test_band_mapper.py
The cleanup of the config continues.  
This PR exhances the `RgbaColorRampDef` style class to also provide the behaviour of the old `HeatMapStyleDef` style class, which has been removed.  Effectively you can now specify a value range instead of an explicit colour map and a default heatmap-style colour map will be generated for you.
Also the `HybridStyleDef` style class has been rejigged to extend the `RgbaColorRampDef` style class instead of the old `HeatMapStyleDef`.
Should be fully backwards compatible with old config files that used the heatmap or hybrid style classes (although I believe no official GA config files do so), except the `"heat_mapped": True,` entry is no longer needed (it is ignored).
=> Heatmap winddown

datacube_wms/ogc.py
A cleanup of the routing code, adding in a framework for future support of multiple versions of protocols, and of OGC-style version negotiation.
Not much to see from the outside as we still only support one version per protocol, but it's a foundation for building WCS2.0 support on.
=> Version negotiation

datacube_wms/product_ranges.py
Changes to `product_ranges` so it doesn't crash on multi_products.
=> Skip multi_products in update_ranges.

datacube_wms/data.py
In the upcoming changes defined in #94 the new_datasource output has been modified, it no longer returns an object with the `_dataset` parameter. The fix for this is to sort datasets prior to getting the datasources. This will also give a small performance boost as we don't have to sort on each measurement. 
This change doesn't require the new datacube-core version.
=> Sort dataset for new datacube support and improved performance

datacube_wms/wms_layers.py
Ignore missing products and multi-products in GetCapabilities.
Ignore products missing pq_products in GetCapabilities.
Ensures that a configuration that requires a datacube product will result in a working GetCapabilities call even if that product is missing.
=> Remove missing products from GetCaps

Dockerfile, requirements.txt, setup.py
`dea-proto` has been trimmed down by moving various helper apps out of main
`dea-proto` lib. Particularly there is no more `aiobotocore` dependency present.
=> Updating version of dea-proto

datacube_wms/data.py
With cases such as fractional cover being pq masked by WOfS, this prevents data from being displayed where the pq mask data does not exist in a particular area or time slice due to mismatches in what data is processed / available.
=> Return empty images if pq_data is missing when it was requested

datacube_wms/legend_generator.py, datacube_wms/templates/wms_capabilities.xml
There were a couple of places the code was looking for the style name in `product.legend` instead of `product.legend['styles']`
Not sure if there a wider implications on particular WMS client interactions?
=> Only show the legend of the current style

datacube_wms/templates/wms_capabilities.xml
A new platform folder was being created for each product layer, instead of a platform containing multiple product layers.
This made it difficult to navigate to layers in GIS packages.
=> Nest products under platform folders

datacube_wms/band_mapper.py, datacube_wms/legend_generator.py, datacube_wms/templates/wms_capabilities.xml, datacube_wms/wms_cfg_example.py, tests/test_legend_generator.py
This PR does 2 things:
* Allows a URL to be provided instead of the style legend (Closes #119)
* For styles not in the list of `product.legend.styles`, advertise a blank URL, to prevent Terria from falling back to `GetLegendGraphic` for the layer.
`GetLegendGraphic` will still work for legends set at the layer level.
=> Per-style legend fixes

datacube_wms/wms_utils.py, tests/test_wms_utils.py
The PR adds support for WMS time range queries, defaulting to the first time, when multiple valid times are found in the requested time range ~~when the time range covers a single time~~.
It supports:
- fixed ranges: `2018-01-10/2019-01-10` 
- fixed ranges with reduced accuracy: `2018-01/2018-03`
- range/duration: `2000/P1Y`, 
- current time: `2019-01-01/PRESENT`
It uses GeoServer's documentation as a guide:
https://docs.geoserver.org/stable/en/user/services/wms/time.html
This will allow use with the QGIS TimeManager WMS client.
Closes #65
=> Support time range queries

datacube_wms/legend_generator.py, datacube_wms/templates/wms_capabilities.xml
No longer provide empty LegendURL strings, as this broke OGC compliance
Don't provide a combined Legend image if not all styles are on it
=> Partial undo LegendURL changes

datacube_wms/wms_layers.py
Noticed when initialising flask server that there is a pandas depreciation warning coming up for .ix. Replaced instances with .loc, outputs are identical.
=> Removing pandas depreciation warning

Dockerfile
1) To ensures maximum CPU utilization, and reduces the chances of being unable to respond to a heartbeat query, update `gunicorn` as follows:
` CMD gunicorn -b '0.0.0.0:8000' --workers=3 --threads=2 -k gevent --timeout 121 --pid gunicorn.pid --log-level info --worker-tmp-dir /dev/shm datacube_wms.wsgi`
2) Install `dea-proto` dependencies using `--extra-index-url` option and remove use of `git+https` in the dependency list
3) Use `pip3` for installation
=> Configure gunicorn to use /dev/shm instead of /tmp

datacube_wms/wcs.py, datacube_wms/wms.py, datacube_wms/wmts.py
Enables getCaps to be cached by load balancers / CDNs for 10 seconds, should improve performance and reduce DB / CPU usage.
=> Enable 10 second cache on getCaps

datacube_ows/band_mapper.py, datacube_ows/ows_cfg_example.py, tests/test_mpl_cmaps.py
New Feature:
- Support string shortcut based reuse of Matplotlib colormaps
- Notes around strange code paths where matplotlib is used and could be shortcut using these name based mappings for legend generation.
=> Addresses Matplotlib ColorMaps support

docs/installation.rst
Added dev docs for OWS using Docker instead of relatively hard to install pip dependencies.
=> #163 Document dev install using Docker

requirements.txt
Reverts opendatacube/datacube-ows#183,
CRITICAL TIMEOUT ERROR is still occuring on dev ows
=> Revert "fixinate gunicorn version to 19.9.0"

datacube_ows/data.py, tests/test_data.py
Add a workaround to pass getfeatureinfo requests being passed to floating point input bands with masking where datacube fails due to bitwise masking being used in:
https://github.com/opendatacube/datacube-core/blob/2890b0b16b3259f9a516fb4315d44b738880c7a1/datacube/storage/masking.py#L220
Need to make datacube more robust to handling floating point input bands particularly for SAR Gamma0 style products.
=> #187 A typecast fix for get featureinfo error

datacube_ows/ows_configuration.py
NaN was not being handled correctly as a nodata value - especially for WCS1.
Fixes issue #205
=> Handle NaN as a nodata value for floating point products.

README.rst, docker-compose.db.yaml
Internally within the composed stack, 
`Postgres` container maps to IP `127.172.0.2` and port `5432`
The benefit of `ports: "${DB_PORT}:5432` is to avoid port clash on the host machine
=> fix chained compose with db

.github/workflows/main.yml, README.rst, check-code.sh, requirements.txt
Closes #238 
- Coverage analysis via pytest-cov
- Publish coverage results to [CodeCov](https://codecov.io/gh/opendatacube/datacube-ows) and show as part of PR's
=> Enable coverage flag

datacube_ows/ows_configuration.py
And provide warnings/notices for redundant or over-ridden config.
=> Read native resolution from ODC metadata. 

datacube_ows/data.py
Fixes two related issues in GetFeatureInfo:
1) `data_available_for_dates` list previously used the bounding box of the extents of the datasets - it now uses the extents.  (Issue #283 )
2) `data_links` list previously gave datasets for all dates AND used the bounding box of the extents to determine inclusion in the list.  Now it's just for the date(s) requested and checks the dataset extents.
Might  have a slight impact on GetFeatureInfo performance, but shouldn't be too bad.
=> Check dataset extents in getfeatureinfo.

datacube_ows/band_mapper.py, datacube_ows/legend_generator.py, datacube_ows/ogc.py, datacube_ows/wms.py, datacube_ows/wms_utils.py, tests/test_legend_generator.py
Support for multi-date (e.g. delta) legends.
1) Support for the GetLegendGraphic pseudo-standard operation has been reinstated. A date list can be specified in the optional "times" parameter.
2) Internal "legend.png" requests can also specify a date count parameter "ndates".
In both cases if no dates are specified, all legends for the style are returned (e.g. regular ndvi AND ndvi delta legends).  Otherwise the legend appropriate for the specified number of dates is used to determine which legend to return.
If the parameters are invalid an http error is returned.
=> Multi date legend

datacube_ows/update_ranges.py
Update_ranges `--schema` option needs to know the database name.  It was simply reading the environment variable `$DB_DATABASE`, which leads to unexpected behaviour on systems making heavy use of `datacube.conf` style configuration.
Update_ranges now uses the datacube core `config.parse_env_params` method to determine the database name.
Fixes Issue #267
=> Update ranges should get database name from odc config when available.

.github/.codecov.yml
I believe this change needs to hit `master` before codecov starts using it.
=> Fix paths for codecov

.github/.codecov.yml, integration_tests/conftest.py, integration_tests/test_update_ranges.py, ows_test_cfg.py
Increase coverage of update ranges tests by calling them from Click runners.
https://click.palletsprojects.com/en/7.x/testing/
=> #287 Cover update ranges with tests

datacube_ows/ogc_exceptions.py
WMTS Exceptions referenced an incorrect Exception XSD URL.  The correct XSD comes from the OWS-Common 1.1.0 spec.
Fixes #308  (and it's a trivial one liner.)
=> WMTS Exception url was wrong - uses OWS-Common 1.1.0

ows_test_cfg.py
Reduce the size of ows_test_cfg for testing purpose only
- remove styles which simulate the same function but with different bands or styles or range value
- remove styles which is a subset of another style
=> Clean up ows_test_cfg

Dockerfile
Is there a way to get Dockerfile to use requirements-dev.txt to avoid setting this version number in two places?  I tried a few things but none of them worked.
=> Update pydev version number in Dockerfile.

datacube_ows/ows_configuration.py, tests/test_ows_configuration.py
First alias in band index is what is displayed in getfeatureinfo.  Using the native name by adding a redundant first alias was broken.
=> Fix Band Index so redundant aliases work as documented.

datacube_ows/data.py
* Don't use pt_native in get_s3_browser_uris because sometimes datasets at the same point but different times have different crs and pt_native is only set based on the last point, time, dataset, combination in feature_info, instead transform the pt to a native point in the get_s3_browser_uris function as needed
* removed accidental comment
Co-authored-by: Ben Leighton <Ben.Leighton@csiro.au>
=> Fix getfeatureinfo crs (#343)

datacube_ows/sql/extent_views/create/011_create_time_view.sql, datacube_ows/sql/extent_views/create/012_create_space_view_raw.sql
Archived datasets from non-EO3 products were not being excluded from the materialised views.
=> Materialised views only excluding archived datasets for EO3 

datacube_ows/band_mapper.py, datacube_ows/data.py, datacube_ows/mv_index.py, datacube_ows/sql/extent_views/create/018_grant.sql, datacube_ows/sql/extent_views/refresh/002_refresh_time.sql, datacube_ows/sql/extent_views/refresh/003_refresh_space.sql, datacube_ows/sql/extent_views/refresh/004_refresh_spacetime.sql, datacube_ows/sql/extent_views/refresh/004_refresh_spacetime_requires_blocking.sql, datacube_ows/update_ranges.py, datacube_ows/wcs1_utils.py, datacube_ows/wcs2_utils.py, docs/database.rst, integration_tests/test_mv_index.py, ows_test_cfg.py, requirements.txt, setup.py, tests/test_mv_selopts.py
Second attempt at using materialised views in OWS searches.
There is a simple flexible search API in `datacube_ows.mv_index`.  For a given product/spatio-temporal query, it can return either:
1) A simple count of number of matching datasets.
2) A list of IDs of the matching datasets.
3) The extent geometry for which there is data within the search spatial window.
4) A list of ODC dataset objects.
Edit: I'm using the views throughout WMS and WCS now.
=> MV search redux

docs/configuration.rst
Half the config documentation is missing from readthedocs.  This might fix it?
=> Documentation not linked from master menu not appearing on readthedocs.

README.rst, docs/cfg_colourmap_styles.rst, docs/cfg_colourramp_styles.rst, docs/cfg_component_styles.rst, docs/cfg_functions.rst, docs/cfg_global.rst, docs/cfg_hybrid_styles.rst, docs/cfg_layers.rst, docs/cfg_styling.rst, docs/cfg_wcs.rst, docs/cfg_wms.rst, docs/configuration.rst, docs/environment_variables.rst, docs/installation.rst
Readthedocs changes filenames on compile from "*.rst" to "*.html".  Therefore internal relative links like "cfg_styling.rst" will fail on RTD.   I've made all links to be explicit links to RTD latest html files. 
(And I've seeded a couple of alternative forms as temporary tests just in case Sphinx does some sensible link translation I haven't found the documentation for.)
=> Readthedocs internal links

datacube_ows/data.py, datacube_ows/query_profiler.py, datacube_ows/wms_utils.py, tests/test_qprof.py
Hopefully useful diagnostic tool.
Whack `&ows_stats=true` on the end of any get map query and the server goes through all the work of loading and transforming the data into an image, but instead of returning that image, returns some profiling data on that specific query.  E.g.:
```
{
"profile": {
"query": 0.3746297359466553, 
"count-datasets": 0.015242815017700195, 
"fetch-datasets": 0.023380041122436523, 
"load-data": 0.23415517807006836, 
"build-masks": 0.020035266876220703, 
"combine-masks": 0.0010516643524169922, 
"apply-style": 0.05451154708862305, 
"write": 0.001939535140991211
}, 
"info": {
"n_dates": 1, 
"n_datasets": 1, 
"write_action": "Write Data"
}
}
```
The `"profile"` section contains real execution times in seconds.  ("query" refers to the (almost) entire processing time - …
=> Add query profiling tool.

datacube_ows/sql/extent_views/create/010_create_new_time_view.sql
EO3 products with a single timestamp were being represented as [time, time+1 day] 24 hour range.  Now a [time, time] instantaneous time range, as for EO products.  Should fix #416
=> Remove "plus one day" bug for scalar-timed EO3 datasets.

.dockerignore, Dockerfile, datacube_ows/__init__.py, datacube_ows/ogc.py, datacube_ows/templates/index.html, requirements.txt, setup.py
For #423   
Will work more smoothly when we publish tags to PyPI.
For now, you must run:
```
echo "version=\"`python setup.py --version`\"" > datacube_ows/_version.py
```
This derives the version number from git.
Should work automagically in Docker.
=> Report version in index page.

datacube_ows/sql/extent_views/create/010_create_new_time_view.sql, datacube_ows/sql/extent_views/create/011_create_new_space_view_raw.sql
Fix for #415
I'm just assuming the new metadata type is the same as eo as far as space and time extents go.
@pindge could you try regenerating the materialised views for the new data with this branch?
=> Handle eo_s2_nrt metadata type in materialised views

datacube_ows/config_toolkit.py, tests/test_styles.py
Config inheritance was failing for concatenable arrays when the parent has no array to concatenate to.
=> Fix deepupdate of concatenatable arrays

.github/workflows/docker.yml
Addresses Functional tests and Docker push section of the CI workflow and accesses dockerhub secrets only from master in main repo preventing PR's from fork blocking.
=> #431 Create new docker push workflow

cfg_parser.py, datacube_ows/band_utils.py, datacube_ows/ows_configuration.py, setup.py
Useful tool. E.g.
Parse the current config file, as per environment variables:
```
datacube-ows-cfg-parse
```
Parse a particular config file (not the python file name, but the python object FQP):
```
datacube-ows-cfg-parse my_cfg_file.ows_cfg
```
Parse syntax only, do not attempt to validate against the database:
```
datacube-ows-cfg-parse -p my_cfg_file.ows_cfg
```
=> Standalone config parser tool for validating config files.

datacube_ows/ows_configuration.py, datacube_ows/templates/wmts_capabilities.xml, datacube_ows/tile_matrix_sets.py, datacube_ows/wmts.py
Draft fix to #451.
This PR now has a tile matrix set that is hopefully VicGrid GeoCortex compatible.   (No specific config change required - you get it automatically if you publish in EPSG:3111).  Let's confirm it works before we go too much further.)
A subsequent PR will add broader unit tests, integration tests and shift the definition of the VicGrid GeoCortex Tile Matrix Set to config instead of having it hard wired into the wmts code.
=> Generalise handing of wmts tile matrix sets

datacube_ows/ows_configuration.py, integration_tests/test_mv_index.py, tests/conftest.py, tests/test_cfg_layer.py, tests/test_cfg_wcs.py
Several old apparently passing tests were actually failing silently.
WCS grids for layers with a native CRS with "vertical coordinate first" (e.g. EPSG:4326) were being coordinate mangled - bug fix.
Haven't quite finished with this chunk of testing work, but I'm finalising the PR because of the major bug fix above.
=> WCS Config tests

datacube_ows/ows_configuration.py, tests/conftest.py, tests/test_cfg_global.py, tests/test_cfg_wcs.py
Opening in draft to track coverage.
=> Complete config tests

Dockerfile, env-build-tool
I don't know if ithis is an acceptable solution, but as per @Kirill888's suggestion, I patched `build-env-tool` to pin the version of `pip`.
=> hotfix geobase env-build-tool to pin pip to version before breakage

datacube_ows/ows_configuration.py, datacube_ows/templates/wms_capabilities.xml, integration_tests/test_wms_server.py
so that bbox terminology bug I fixed recently was actually a feature.
Fixes #477
=> WMS BoundingBox uses "X" to mean "first coordinate"

datacube_ows/data.py, datacube_ows/ows_cfg_example.py, datacube_ows/ows_configuration.py, datacube_ows/wcs1.py, datacube_ows/wcs1_utils.py, datacube_ows/wcs2.py, datacube_ows/wcs2_utils.py, docs/cfg_layers.rst, tests/test_cfg_cache_ctrl.py
New configuration entries supporting progressive cache control headers, prioritising expensive resource-intensive queries for caching.
See documentation changes for details.
=> Progressive cache control

datacube_ows/ows_configuration.py, tests/test_cfg_layer.py
Various combinations of using single-product configs in a multi-product layer and vice versa were failing silently, leading to unhelpful error messages.  This should now be addressed.
=> Product products checks

datacube_ows/product_ranges.py
=> Update ranges failed badly if config referenced a non-existant product name

datacube_ows/cfg_parser.py, integration_tests/test_cfg_parser.py
In response to #492
New behaviour:
`datacube-ows-cfg-parse -f`
Pretty-print the folder/layer hierarchy (without styles).
`datacube-ows-cfg-parse -s`
Pretty-print a list of named layers and their styles.  Does not include the folder hierarchy or non-named folder-layers.
`datacube-ows-cfg-parse -s -f`
Pretty-print the folder/layer hierarchy, with styles for each named layer.
Folder titles are printed with a prefixed "*".  Style names are printed with a prefixed ".".  Layer names are printed with no prefix, but with the ODC product names in brackets as a suffix.
`--styles` is equivalent to `-s` and `--folders` is equivalent to `-f`.  The `-s` and `-f` flags are NOT compatible with the `-p/--parse-only` flag.
=> Optionally display layer/style lists with cfg_parser.

datacube_ows/styles/ramp.py, tests/test_legend_generator.py
Fix for bug #484 
Affected colour ramp styles where the legend end value does not appear in the explicit colour ramp.
=> Fix ramp colour-split bug

datacube_ows/startup_utils.py, docker-compose.yaml, docs/environment_variables.rst, tests/test_startup.py
Pass AWS credentials from local environment variables to datacube-ows.
Check AWS_REQUEST_PAYER environment variable and call
datacube.utils.rio.configure_s3_access accordingly.
Delete AWS_NO_SIGN_REQUEST environment variable if set to "no". GDAL
seems to always use unsigned requests if this variable is present, even if
set to "no" or "".
=> Fixes for datacube AWS configuration

datacube_ows/band_utils.py, docs/cfg_functions.rst, tests/test_band_utils.py
1) Use decorators to improve readability and code-reuse in band_utils.py
2) Add (decorator) support for using an index as a intensity modifier to a band.
=> Band util decorators

datacube_ows/data.py, datacube_ows/styles/base.py, docs/cfg_layers.rst, tests/test_data.py
1. Display flag data as flag data for layers with colourmap styles. (bug fix)
2. Remove support for "ignore_info_flags" config element.  After multi-product masking it doesn't work and doesn't even really make sense.
3.  Improve GetFeatureInfo output for flag bands - now more informative and more consistent across metadata types.
=> Fix flag output in GetFeatureInfo

datacube_ows/styles/colormap.py, docs/cfg_colourmap_styles.rst, tests/test_styles.py
1. `"mask": True` in a colourmap style is now exactly equivalent to `"alpha": 0.0`.
2. Colour map legends now include only rules that have a (non-blank) title and abstract; AND have alpha != 0.
3. Colour map legends are now rendered in the *REVERSE* of the rule order.
4. Colour map legend labels now omit the dash if the rule only one of title and abstract is non-blank.
5. Titles are now required (but may be blank and need not be unique).  Abstracts are now optional.
6. General cleanup and refactor.
=> Fix mask flag in value map

datacube_ows/styles/base.py
Enum masking was not working for multidate (e.g. delta) queries.
=> Fix Enum masking for multidate queries.

datacube_ows/styles/colormap.py, docs/cfg_colourmap_styles.rst, tests/test_style_api.py
Addressing issue #524 
Example of new syntax:
```
{
"name": "fmask",
"title": "FMASK visualisation",
"abstract": "Visualisation of fmask classification",
"value_map": {
"oa_fmask": [
{
"color": "#0000FF", # blue
"title": "Water",
"values": [5],
},
{
"color": "#9090FF", # pale-blue
"title": "Snow",
"values": [4],
},
{
"color": "#000000", # black
"title": "Cloud and Shadow",
"values": [2,3],
},
{
"color": "#00C000", # bright green
"title": "Valid",
"values": [1],
},
{
"color": "#000000",
"mask": True, # transparent
"title": "No Data",
"values": [0],
},
]
}
}
```
=> Value map enum support

datacube_ows/band_utils.py, tests/test_band_utils.py
Multi-date requests are currently not date-order-sensitive.
Can now flip the delta direction with the `time_direction` kwarg:
```
{
"function": "datacube_ows.band_utils.multi_date_delta",
"kwargs": {
"time_direction": 1,    # Use >0 for earliest - latest, <0 for latest - earliest
}
```
Means you can at least have separate styles for forward and backwards subtractions.
=> delta can now take a kwarg to choose subtraction direction.

datacube_ows/styles/expr.py, datacube_ows/styles/expression.py, datacube_ows/styles/ramp.py, docs/cfg_colourramp_styles.rst, requirements.txt, setup.py, tests/test_style_api.py
Allow ramp styles to take an "expression" string.  E.g.
```
"index_expression": "(nir-red)/(nir+red)",
```
(`index_expression` can be used instead of `index_function` and `needed_bands`.) 
This is a first step towards user band math. (#491)
=> Expression based ramp styles

datacube_ows/data.py
GetFeatureInfo reports the source product for the clicked pixel.
However, this was using the `platform.code` metadata element that is present on Sentinel-2 products but not C3 Landsat products.
The code now falls back politely and only uses metadata that will always be present if `platform.code` is not available.  Behaviour for Sentinel-2 combined multi-product layers will not change.
=> Multiproduct source product determination was broken in C3.

datacube_ows/data.py
Fixes ugly error when the spatial extent of the main data is bigger than the spatial extent of a time-independent mask product.
Will probably incur a coverage hit unfortunately - we don't have a really good solution for testing this part of the codebase yet.
=> Handle case where data extent exceeds time-ignored mask product extent

.github/workflows/test.yml
A CodeCov token not required for public repositories uploading from Travis, CircleCI, AppVeyor, Azure Pipelines or GitHub Actions
The existing CodeCov token will be regenerated
Remove the CodeCov secret and remove from the codecov-action
=> removes the codecov token from ows

datacube_ows/ogc_utils.py, datacube_ows/styles/api/base.py, datacube_ows/styles/base.py, docs/cfg_style_api.rst, tests/conftest.py, tests/test_ogc_utils.py, tests/test_style_api.py
For #590 
```
images = apply_ows_style(style, data, loop_over="time")
pngs = xarray_image_as_png(images, loop_over="time")
for i, png in enumerate(pngs):
with open(f"filename{i:02}.png", "wb") as fp:
fp.write(xarray_image_as_png(image)
```
=> Allow looping over a dimension to do bulk processing in API.

Dockerfile, requirements.txt
- remove duplicate copy in `env_builder`
- update requirement, gevent to use latest version to address
```
(base) ubuntu@dea-dev-eks:~/datacube-ows$ docker run datacube-ows
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
```
=> fix ows build

datacube_ows/ows_cfg_example.py
tried to run it ```duct names entry missing in named layer mangrove_cover
[2021-05-20 02:19:14 +0000] [8] [ERROR] Exception in worker process
Traceback (most recent call last):
File "/env/lib/python3.8/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
worker.init_process()
File "/env/lib/python3.8/site-packages/gunicorn/workers/ggevent.py", line 146, in init_process
super().init_process()
File "/env/lib/python3.8/site-packages/gunicorn/workers/base.py", line 134, in init_process
self.load_wsgi()
File "/env/lib/python3.8/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
self.wsgi = self.app.wsgi()
File "/env/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
self.callable = self.load()
File …
```
=> add 3111 to cfg example

requirements.txt
its faulty 
```
datacube-ows_ows_1 exited with code 1
ows_1       | 
ows_1       | Error: class uri 'eventlet' invalid or not found: 
ows_1       | 
ows_1       | [Traceback (most recent call last):
ows_1       |   File "/env/lib/python3.8/site-packages/gunicorn/util.py", line 99, in load_class
ows_1       |     mod = importlib.import_module('.'.join(components))
ows_1       |   File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
ows_1       |     return _bootstrap._gcd_import(name[level:], package, level)
ows_1       |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
ows_1       |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
ows_1       |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
ows_1 …
```
=> remove eventlet

datacube_ows/ogc_utils.py
Timezone detection failures happen occasionally.  They were not being logged in a way that was helpful.
=> Better logging on timezone detection failure.

Dockerfile
Installation of pydevd is supposed to be dependent on environment.
First, we were always installing pydevd, then we were never installing it.
This combination seems to work both ways.
=> Fix env-controlled install of pydevd.

datacube_ows/data.py
Problem: When data does exist for the main product, but does not exist for an associated tie-aware mask product, an unhandled error occurs.
This is an implementation of "solution 2" as discussed on Slack:
> The question is what should OWS do in this case:
> 1. Act as if there is no data (return a blank tile); or
> 2. **Render the data without masking.**
This is consistent with the way the analogous issue is handled for ignore-time mask products.
=> Attempted fix for main-product/mask-product time extent mismatches.

docs/style_howto_color_map.rst, docs/style_howto_components_nonlinear.rst
From second OWS workshop.
Fixes to broken examples, mis-spellings.  
Make usage more consistent. 
Remove irrelevancies
Update example images
=> Howto corrections

datacube_ows/styles/api/base.py
Jupyterhub plotting is broken - overrides aspect ratio.
Allow user to pass in aspect ratio, and use 1:1 pixel aspect ratio of data  image as default.
I want to release this before I give the styling workshop as part of the ODC conference.
=> Correct aspect ratio on image plot in Jupyterhub/sandbox.

datacube_ows/ows_configuration.py, datacube_ows/wcs1_utils.py, datacube_ows/wcs2_utils.py, docs/cfg_wcs.rst, tests/test_cfg_global.py
Global config option to deactivate tiff statistics.
Tradeoff is that statistics improve interoperability with some GIS clients (e.g. QGIS), but calculating statistics uses additional memory usage on large coverage requests.
Default is to calculate statistics. If you want to maximise the size of the GeoTIFF coverages that you can serve for a given memory allocation, you can set "calculate_tiff_statistics" in the global "wcs" section to False.
Addresses issue #653 for @valpesendorfer
=> Make calculating tiff statistics optional

datacube_ows/data.py, datacube_ows/ows_configuration.py, requirements.txt, setup.py, tests/test_cfg_layer.py
Addresses #648
Use rasterio to generate shaded extent polygons for resource limit-exceeding WMS/WMTS queries.  This removes scikit-image as a dependency.
=> Rasterio polygons

datacube_ows/ogc_utils.py, tests/test_ogc_utils.py
Pillow isn't as smart about array coordinate order as Rasterio was.  Tiles were getting coordinate swapped.
=> Fix Pillow coordinate order issues.

datacube_ows/ows_configuration.py, datacube_ows/styles/hybrid.py, datacube_ows/styles/ramp.py, datacube_ows/templates/wms_capabilities.xml, datacube_ows/wcs1_utils.py, docs/cfg_layers.rst, tests/conftest.py, tests/test_cfg_layer.py
Addresses #673
Can now add to layer config:
```
"default_time": "latest",    # Default behaviour - use the most recent available date as the default time, OR:
"default_time": "earliest", # Use the earliest available date as the default time, OR:
"default_time" : "2020-01-01",   # Use an explicitly defined date as the default time.
```
The default date is only published in metadata by WMS.
The default also applies to WMTS, and WCS1 requests with no user-selected time, but there is no way for a client to know what the default date is.
WCS2 requests with no dates select ALL available dates, as per the spec.
=> Wms default time

.env_ows_root, .env_simple, docker-compose.yaml, docs/environment_variables.rst
- we have been copying the `ows_refactored` folder into `datacube-ows` to start docker-compose and then copy the changes back to `dea-config` git clone to make the pr, this pr resolves the double handling and mounts external cfg folder directly.
=> enable docker-compose to mnt external config

datacube_ows/styles/base.py
With "adjusted zoom level" resource management, animations no longer need to be considered experimental.
(On the server side, still waiting for clients to catch up.)
=> Remove "experimental" warning on animations.

datacube_ows/startup_utils.py, docs/environment_variables.rst, tests/test_startup.py
Default behaviour (AWS_NO_SIGN_REQUEST) now matches boto3 conventions.  (i.e. default behaviour = signed requests).
A warning message is logged if the `$AWS_NO_SIGN_REQUEST` variable does not exist.
Default previously was unsigned requests for some reason I've now forgotten.
=> Change default behaviour of AWS_NO_SIGN_REQUEST to match everything else

datacube_ows/data.py
This should fix the immediate bug affecting Terria Export via WCS1.
I think there will still be issues with WCS queries returning flag-band data from the main product, but I need to think about that a bit more, and I want to get this fix out.
=> Fix WCS for queries against layers with flag band in the main product.

datacube_ows/ows_configuration.py, datacube_ows/wcs1_utils.py, datacube_ows/wcs2_utils.py, docs/cfg_layers.rst, integration_tests/cfg/ows_test_cfg.py, tests/test_cfg_layer.py, tests/test_cfg_wcs.py
WCS1.x standard is silent on behaviour if user doesn't explicitly list desired bands - default_bands entry provided the answer.
WCS2.x standard is pretty clear that the default behaviour should be to return all available bands.
This PR removes the configured default band list, makes WCS2 more standards-compliant, and makes WCS1 behaviour consistent with WCS2.
=> Remove wcs default_bands config entry, as per issue #725

.github/workflows/dive.yml, .github/workflows/test.yml, Dockerfile, dive-ci.yml, docker-compose.db.yaml, docker-compose.yaml, requirements.txt, tests/test_wcs_scaler.py
- setup dockerfile with `osgeo/gdal` as base
- adjust dive docker value
- - highestwastedbyte increase from 16mb to 45mb
- - highestuserwastedpercent lower from 0.2 to 0.05
- fix docker-compose.db.yaml by adding `ports`
- remove `image` from `docker-compose.yaml`
- pin `fsspec and numpy` version
- adjust pytest to allow projection value decimals
- adjust docker image final size allowed by increasing from 1.1gb to 1.15gb
=> setup docker image based on gdal

datacube_ows/wcs2.py, setup.py, tests/test_cfg_inclusion.py
For #760 
Needed for Terria upgrade testing/demo.
=> Apply configured response headers to WCS2 GetCoverage responses.

.github/workflows/lint.yml, Dockerfile, datacube_ows/config_utils.py, setup.py, tests/conftest.py, tests/test_cfg_inclusion.py
Remove S3FS-based testing and improve unit tests of get_file_loc.
get_file_loc was not actually checking for non-S3 urls.
=> Replace s3fs tests

datacube_ows/wcs1_utils.py, datacube_ows/wcs2_utils.py
Dataset count resource limit for WCS was not being applied because the presence of lowres mosaic data was not being checked correctly.  Hard bit of code to test with our current test infrastructure.
=> Soft-limit (dataset count) check for no lowres data was broken.

datacube_ows/styles/base.py, datacube_ows/styles/colormap.py, datacube_ows/styles/ramp.py, docs/cfg_colourmap_styles.rst, docs/cfg_colourramp_styles.rst, tests/conftest.py, tests/test_multidate_handler.py, tests/test_style_api.py, tests/test_styles.py, tests/utils.py
Non-animated multidate support for colour-map styles.
In addition to the standard animated handlers previously supported by all style types, this PR introduces two additional approaches to produce an non-animated image from a multi-date request:
1. Using a variant of the `value_map`_ entry used for the single-date case. This is a much simpler way of achieving most use cases.
2. Using an aggregator function, which allows for fully customisable behaviour but requires writing Python code.
A value_map in a multi-date handler has the same general structure as the
single date value_map.  The handler must serve a single
number of date values.  The discussion here will assume an `allowed_count_range``
of `[2, 2]`, but higher values should work.
The ``flags`` or ``values`` entry for each rule is …
=> Value map multi-date handlers

datacube_ows/ogc.py, datacube_ows/startup_utils.py, tests/test_startup.py
Simplify metric names and add a common prefix `ows_`.
Convert case insensitive parameters serving as labels to all upper case to simplify queries.
=> Prometheus refactor.

HISTORY.rst, datacube_ows/ogc.py
Ready for 1.8.23.2 interim release.
=> Remove OGC metric from Legend URLS. Update History.rst.

datacube_ows/ogc.py
Layer name not being captured correctly by Prometheus for GetFeatureInfo requests (for some clients - Terria sets both "layers" and "query_layers" so requests from Terria clients work fine.)
=> Minor fix to prometheus metrics for GetFeatureInfo requests.

datacube_ows/styles/base.py, datacube_ows/styles/colormap.py, datacube_ows/styles/ramp.py, datacube_ows/templates/wms_capabilities.xml, datacube_ows/templates/wmts_capabilities.xml, docs/cfg_colourmap_styles.rst, tests/test_legend_generator.py, tests/test_multidate_handler.py, tests/test_style_api.py
Fairly major refactor of legend generation factor.  Underlying motivation is to allow all text elements in auto-generated legends to be translatable, however this PR is just the preparatory refactor - the actual translation work will be done in a subsequent PR.
The refactored implementation should be mostly compatible with the previous implementation, except as noted below.
Functional changes:
1) Long-deprecated "legacy" style legend configurations now always trigger an config exception.  This was only partly the case previously.
2) The default width of colour-map legends is now 4 inches (at 100dpi) to match the default for colour-ramp legends (previously 3 inches).
3) Colour-map legends now support a legend title (previously legend titles were only supported for colour-ramp legends). …
=> Legend Generation Refactor.

datacube_ows/cfg_parser_impl.py, datacube_ows/config_utils.py, datacube_ows/ows_configuration.py, datacube_ows/styles/base.py, datacube_ows/styles/colormap.py, datacube_ows/styles/ramp.py, docs/cfg_styling.rst, docs/configuration.rst, integration_tests/cfg/ows_test_cfg.py, integration_tests/test_cfg_parser.py, integration_tests/test_layers.py, integration_tests/test_wms_server.py, tests/test_style_api.py
Leverage recent refactor to provide internationalisation of legends.  (Addresses issue #771)
Includes some unrelated legend-handling bug fixes and documentation corrections.
Most text in config that can be written to legend is now recognised as translatable metadata by the translation engine:
* Legend titles (colour ramp and colour map legends)
* Legend units (colour ramp styles)
* Legend tick labels (colour ramp styles)  (See note below)
* Rule labels (colour map styles) (for non-transparent rules only)
Note: prefixes, suffixes and labels are combined into a single label string for translation purposes, and combined label strings that contain no alphabetic characters are explicitly excluded from the translation engine.
For manual legends, you can now specify a separate external image url …
=> Legend translation

datacube_ows/ows_configuration.py, tests/test_cfg_global.py
srsName for `EnvelopeWithTimePeriod` in WCS1 DescribeCoverage output was blank.
=> Fix WCS1 regression

datacube_ows/styles/base.py
Support for translatable manual legends broke manual legends in non-internationalised deployments.  This should fix.
=> Don't try to read locale if babel is uninitialised.

datacube_ows/wcs1.py, datacube_ows/wcs1_utils.py, datacube_ows/wcs2_utils.py, integration_tests/test_wcs_server.py
Multidate requests were broken in both WCS1 and WCS2 (and have been for quite some time).
Addresses issue #798
Properly testing multi-date requests is impossible without extending the integration test database. (see issue #800)
=> Wcs multidate fixes

datacube_ows/wcs1_utils.py, datacube_ows/wcs2_utils.py, integration_tests/test_wcs_server.py, tests/test_wcs_scaler.py
int8 bands should almost always actually be uint8, but adding support anyway.
Was supposedly a simple (2 line) fix, but ended up bogged down in a whole bunch of externally-triggered testing issues.
=> Add support for int8 type bands to WCS GeoTIFF output.

integration_tests/test_wcs_server.py
I had to temporarily deactivate the WCS XSD validation tests because `schemas.opengis.net` was down for several hours today.
It's back now, so reverting.
=> schemas.opengis.net is back up - restoring deactivated tests.

Dockerfile, README.rst
Old README included a command in the docker instructions that simply won't work as written.  Issue reported on Slack.
=> Remove confusing command from README docker instructions.

datacube_ows/ogc.py
- `request.environ.get('HTTP_X_REAL_IP')` captures requester ip on a local docker container
- `request.environ.get('HTTP_X_FORWARDED_FOR')` captures request IP forwarded by ingress/loadbalancer
- `request.environ.get('REMOTE_ADDR')` is standard internal IP address
```
[2022-03-30 02:54:05,019] [INFO] ip: 49.2.70.36 request: http://ows-iptest.dev.dea.ga.gov.au/wms?request=GetCapabilities&service=WMS&version=1.3.0 returned status: 200 and took: 1100 ms
[2022-03-30 02:54:06,063] [INFO] ip: 10.95.72.77 request: http://10.95.85.173:8000/ping returned status: 200 and took: 17 ms
[2022-03-30 02:54:06,698] [INFO] ip: 10.95.7.197 request: http://10.95.85.173:8000/ping returned status: 200 and took: 2 ms
```
=> add more option for logging ip

datacube_ows/ogc_utils.py, datacube_ows/ows_configuration.py, datacube_ows/resource_limits.py, datacube_ows/wms.py, datacube_ows/wmts.py, docs/cfg_wms.rst, integration_tests/cfg/ows_test_cfg.py, integration_tests/test_wms_server.py, integration_tests/test_wmts_server.py, tests/test_cfg_global.py
Add configurable cache hints for WMS GetCapabilities response, as requested by @valpesendorfer .
Edit top-level `wms` config section to add:
```
"wms": {
....
"cap_cache_maxage": 300,    # 300 seconds = 5 minutes
}
```
Default is 0, which explicitly returns "nocache".
This applies to WMS and WMTS only. Similar support may be implemented in future for the WCS XML requests.
=> Getcap caching

datacube_ows/mv_index.py
Requests for tiles that overlap with the grid boundary for at least one dataset but do NOT overlap with the stored extent of any datasets resulted in an error.  This is now fixed.
In theory could be fixed by making the materialised view queries smarter, but I've handled in mv_search.
Can't explicitly test as no data in the test database has the required geometry.
=> Handle empty polygon intersection in mv_search with EXTENT select mode.

datacube_ows/sql/extent_views/create/011_create_new_space_view_raw.sql
Should result in more accurate/less blocky extent polygons when resource limits are exceeded.
Requires re-running `datacube-ows-update --schema --role rolename`.  (Regenerating the schema is done in-place and does not entail any service downtime.)  and then `datacube-ows-update`.   There is no need to re-run with the `--views` option first, as rebuilding the schema has the same effect.
Results in more accurate extents for all EO3 products and most DEA EO products, with some flow-on efficiency gains from more accurate geospatial dataset search.
=> Extract more accurate extent polygons into the materialised views where possible

datacube_ows/legend_utils.py, tests/test_legend_generator.py
Two bugfixes with Remote Legend URLs:
* Raise warning instead of failing when external legend url is not PNG.
* Clearer error reporting when reading from external url fails.
=> Improve usability of external legends.

datacube_ows/product_ranges.py
Hopefully fixes (or at least mitigates) #824
1. If a crs.valid_range is available, use the intersection of the initial boundingbox and the valid_range.
2. If a crs.valid_range is not available and the projected bounding boxes includes an infinity or an Nan coordinate, use a very large float (with the appropriate sign).
Otherwise the calculated projected coordinate should be fine.
=> Attempt to sanity-check and sanitise bounding box ranges for global datasets

datacube_ows/product_ranges.py
Fixes #831
In `datacube-ows-update` when caching product bounding boxes for published CRSs, CRS bounding boxes are now skipped where the extent of the layer is entirely outside the valid area of the CRS (if a valid area is available).
No other checks for CRS validity are made, e.g.
1) when determining which CRSs to list as supportedin the WMS Capabilities documents, all published CRSs are still listed as available in all top-level layers (and therefore inherited by all non-top-level layers), even if there is no bounding box available for that  CRS.
2) when processing a request. As long as the request bbox can be successfully converted to a valid EPSG:4326 polygon the request is handled smoothly, no checking for CRS validity is applied.
=> Skip invalid CRS extents.

Dockerfile, dive-ci.yml
Latest osgeo/gdal Docker image is based on Ubuntu 22.04 with python3.10 and breaks all our Docker scripts.
We will have to do the hard yards of adapting our Dockerfiles for the new base image some time soon but to avoid blocking other work I have temporarily pinned the Docker base image to the last 20.04-based tag.
=> Fix osgeo/gdal docker version.

datacube_ows/ows_configuration.py, datacube_ows/utils.py, tests/test_utils.py
Sort multiproduct datasets by product (according to the order of the provided product list)
Coupled with `manual_merge` and appropriate band aliases in the ODC metadata, this allows combining products from different families (e.g. a combined Landsat/Sentinel-2 layers, with Sentinel-2 always taking precedence where available).
Further work required to support band-mapping between heterogenous products.
On hold until Docker issues resolved.
=> Sort multiproduct datasets by product

datacube_ows/data.py, datacube_ows/ows_configuration.py, datacube_ows/styles/base.py, docs/cfg_layers.rst, tests/conftest.py, tests/test_cfg_bandidx.py
There are separate band aliasing implementations in core and OWS and they don't play nicely together.  In particular it is difficult/impossible to create multiproduct layers from heterogeneous products (e.g. landsat and sentinel2).
This is a first attempt to address this.
=> Smarter band mapping for hetrogenous multiproducts.  Passes unit tests.

datacube_ows/protocol_versions.py, tests/test_protocol_versions.py
Invalid version request parameters in an otherwise OGC-like request previously resulted in unhandled 500 errors.
A fairly brute force approach that tends towards using the lowest available version.
=> Check for invalid OGC version parameters and make them valid.

integration_tests/cfg/ows_test_cfg.py, setup.py
Rasterio-1.3.0 is buggy.  See #851.  1.2.x is fine and the main branch is fine at time of writing, so 1.3.1 should be fine too.
Also commented out a redundant config entry in the integration test config file.
=> Block rasterio 1.3.0 which has broken warp implementation.

setup.py
Xarray 2022.6.0 includes major refactors which have introduced a number of regression bugs (version blocked).
lark-parser is now just called lark.
Removed some other old pins to see what happens.
=> Update library dependencies based on recent changes to core dependencies

datacube_ows/startup_utils.py
=> make sentry ignore geom error from shapelh

datacube_ows/band_utils.py, docs/cfg_functions.rst, tests/test_band_utils.py
Added `pre_scaled_norm_diff` to `band_utils` to allow the calculation of normalised difference on bands which require scaling first, e.g., USGS LS8 C2 L2 SR. This was suggested by @SpacemanPaul in Slack.
Fixes #880.
The pre-commit hooks failed on most files (that I did NOT modify) so I committed without the checks. However, I ran `black` and `isort` on the code sections I wrote, and only these sections.
This branch can be deleted after merging.
=> Added pre_scaled_norm_diff to band_utils.

.env_ows_root, .env_simple, datacube_ows/startup_utils.py, docker-compose.yaml, tests/test_startup.py
Fixes: https://github.com/opendatacube/datacube-ows/issues/869
captured error message: "'LGEOS380' object has no attribute 'GEOSGeom_destroy'"
- add SENTRY_DSN to `.env`
- fix the test case to reflect the correct reported error
```
where 'event' = <function before_send at 0x7f16f99064d0>('event', {'exc_info': (<class 'AttributeError'>, AttributeError("type object 'LGEOS380' has no attribute 'GEOSGeom_destroy'"), <traceback object at 0x7f16ec3cff40>)})
```
- simplify the condition to allow all the `GEOSGEOM_destroy`
https://github.com/shapely/shapely/blob/f02c4c72d29862ade0708ce777d0316fbba44fef/shapely/geos.py#L633
https://github.com/shapely/shapely/blob/f02c4c72d29862ade0708ce777d0316fbba44fef/shapely/geos.py#L766
https://github.com/shapely/shapely/blob/f02c4c72d29862ade0708ce777d0316fbba …
=> refine sentry ignore

datacube_ows/styles/api/base.py, datacube_ows/styles/ramp.py
Attempt to fix legends-not-rendering in notebooks issue #861.
Setting `nbAgg` programmatically caused too many issues with testing, but I've removed the `use("Agg")` call from the top of ramp.py, so hopefully that will address the issue also.
=> Attempt to fix notebook rendering - Issue #861

datacube_ows/sql/extent_views/create/010_create_new_time_view.sql, datacube_ows/sql/extent_views/create/011_create_new_space_view_raw.sql
New DEA Sentinel2 Collection3 products use an extended EO3 metadata type, which needs to be added to the MV definitions.
=> Add new S2C3 metadata type to MV definitions.

check-code-all.sh, docs/deployment.rst, docs/index.rst
----
:books: Documentation preview :books:: https://datacube-ows--898.org.readthedocs.build/en/898/
=> add instruction to deploy ows with helm

.github/workflows/docker.yml
- get docker tag from datacube-ows-update version within built docker image instead of git 
- remove unused env
----
:books: Documentation preview :books:: https://datacube-ows--907.org.readthedocs.build/en/907/
=> Align docker image tag with ows version

HISTORY.rst, datacube_ows/__init__.py
Update default version number and HISTORY.rst, ready for 1.8.32 release.
----
:books: Documentation preview :books:: https://datacube-ows--910.org.readthedocs.build/en/910/
=> For 1.8.32

datacube_ows/wcs2_utils.py, integration_tests/test_wcs_server.py
Making WCS2 ignore style parameter again, as @robbibt prefers it that way.
----
:books: Documentation preview :books:: https://datacube-ows--915.org.readthedocs.build/en/915/
=> Ignore WCS style parameter.

tests/conftest.py
np.bool is deprecated - use bool.
----
:books: Documentation preview :books:: https://datacube-ows--918.org.readthedocs.build/en/918/
=> Make Numpy 1.24.0+ compatible.

datacube_ows/data.py, datacube_ows/mv_index.py, datacube_ows/query_profiler.py, datacube_ows/startup_utils.py, setup.py, tests/test_startup.py
1. Query Profile objects can now be read like a dictionary.
2. Access SQLAlchemy connection object as a context manager in mv_index.py to ensure proper resource cleanup.
3. Improve ows_stats output for multi-product layers.
Initially I also tried some changes to use flask-babel-3.0.0 but encountered [Flask-Babel Issue #213](https://github.com/python-babel/flask-babel/issues/213)) so I have pinned to `<3.0`
----
:books: Documentation preview :books:: https://datacube-ows--922.org.readthedocs.build/en/922/
=> Miscellaneous cleanup/code maintenance

setup.py
Use latest datacube version to remove sqlalchemy-2.0 from build images.
----
:books: Documentation preview :books:: https://datacube-ows--923.org.readthedocs.build/en/923/
=> Bump to datacube-1.8.10

datacube_ows/templates/wms_capabilities.xml
The previously merged PR (#933) added white space to time value lists in WMS GetCaps responses.
This was intended to make GetCaps documents including layers with large numbers of time slices more easily navigable and perusable by human readers.  While it succeeded on this count, padding lists like this is not discussed in the WMS standard and client applications are well within their rights to fail when confronted with them.
This PR reverts this change and restores standards-compliance in GetCaps documents.
----
:books: Documentation preview :books:: https://datacube-ows--936.org.readthedocs.build/en/936/
=> Remove whitespace from WMS GetCaps date lists.

HISTORY.rst, datacube_ows/__init__.py
Preparing for 1.8.34 release.
Updated default version number and release notes.
----
:books: Documentation preview :books:: https://datacube-ows--937.org.readthedocs.build/en/937/
=> For 1 8 34 release

docs/requirements.txt, wordlist.txt
fix history page not rendering list correctly, see https://datacube-ows.readthedocs.io/en/latest/history.html
----
:books: Documentation preview :books:: https://datacube-ows--938.org.readthedocs.build/en/938/
=> pin docutils version

datacube_ows/ogc_utils.py, setup.py
Since `timezonefinderL` is deprecated and the same functionality was migrated to https://github.com/jannikmi/timezonefinder
related to #947 
----
:books: Documentation preview :books:: https://datacube-ows--948.org.readthedocs.build/en/948/
=> update dependency timezonefinder

HISTORY.rst, datacube_ows/__init__.py
Was hoping to squeeze in #945 but it requires too much other cleanup work.  Ready for maintenance release.
----
:books: Documentation preview :books:: https://datacube-ows--950.org.readthedocs.build/en/950/
=> Update HISTORY.rst and default version for 1.8.35 release.

.readthedocs.yaml, Dockerfile, check-code-all.sh, datacube_ows/ogc.py, datacube_ows/startup_utils.py, docker/database/Dockerfile, setup.py
1. Docker image builder was based on unsupported Ubuntu 22.10 - switch back to LTS release 22.04
2. Remove dependency on `flask-log-request-id` package.  This package appears to be orphaned (not updated since 2019), no longer supports the most recent versions of Flask, and has never been used by DEA.  This means that the X-REQUEST-ID response header will no longer be set.  If you make use of this header in your OWS deployments, please raise an issue and we will find another way to populate it.
3. Changed test db build to use `--ignore-lineage` instead of `--confirm-ignore-lineage`.
----
:books: Documentation preview :books:: https://datacube-ows--954.org.readthedocs.build/en/954/
=> Update Docker image

.pre-commit-config.yaml, HISTORY.rst, datacube_ows/__init__.py, datacube_ows/startup_utils.py, docs/environment_variables.rst, tests/test_startup.py, wordlist.txt
Update HISTORY.rst and increment default version number.
----
:books: Documentation preview :books:: https://datacube-ows--956.org.readthedocs.build/en/956/
=> For 1 8 36

.pre-commit-config.yaml, HISTORY.rst, datacube_ows/startup_utils.py, docs/environment_variables.rst, tests/test_startup.py, wordlist.txt
As raised in #953, the `$PYDEV_DEBUG` environment variable's value was not checked  - setting it to anything other than an empty string resulted in debugging being turned on.  As the examples in documentation set it to "yes", this caused confusion with explicitly setting the environment variable to e.g. "no" resulted in debugging being turned on.
This PR checks for the following values: "N", "NO", F" and "FALSE" (evaluated case insensitively) and treats them as deactivating debugging.
(This PR also manually applies the pre-commit updates raised by pre-commit-ci in #951)
----
:books: Documentation preview :books:: https://datacube-ows--955.org.readthedocs.build/en/955/
=> Pydev debug 

.github/workflows/dockerfile-lint.yml, .github/workflows/lint.yml, .github/workflows/pypi.yml, .github/workflows/pyspy-profiling.yaml, .github/workflows/scan.yml
Some github checks are broken.  This PR consolidates recent dependabot updates into a single PR so I can figure out why checks are failing.  
Later commits will hopefully fix the broken checks as well.
----
:books: Documentation preview :books:: https://datacube-ows--966.org.readthedocs.build/en/966/
=> Consolidate recent dependabot PRs, resolve broken GH Checks

.github/workflows/docpreview.yaml
This is part of the documentation for the action:
https://github.com/readthedocs/actions/tree/v1/preview
=> CI: set permissions for docpreview

.github/dependabot.yml
Dependabot can apparently update versions
in Dockerfile, see trivy for examples:
https://github.com/aquasecurity/trivy/pulls?q=is%3Apr+is%3Aclosed+dependabot+label%3Adocker
----
:books: Documentation preview :books:: https://datacube-ows--975.org.readthedocs.build/en/975/
=> dependabot: update Dockerfile

datacube_ows/startup_utils.py
Metrics are not logs!
Currently, OWS pods are exporting ~5k metrics each due to a misconfiguration, unreasonably requiring Prometheus to retain multiple separate time-series per HTTP path. High cardinality information (individual HTTP paths) belongs in logs but not metrics.
This change makes OWS consistent with datacube-explorer: 
https://github.com/opendatacube/datacube-explorer/commit/6051dd65dcbedef9bb007b50ed47461062b0b91d
----
:books: Documentation preview :books:: https://datacube-ows--978.org.readthedocs.build/en/978/
=> Label metrics by endpoint not path

datacube_ows/data.py, datacube_ows/utils.py
Some minor cleanup that I made while investigating #979.
Clean up when we use numpy `datetime64`s and when we use python `datetime`s
NB. I think the complete fix for #979 will require https://github.com/opendatacube/datacube-core/pull/1521
=> Timezone handling cleanup.

HISTORY.rst, datacube_ows/__init__.py
Update HISTORY.rst and default version number, ready for 1.8.37 release.
----
📚 Documentation preview 📚: https://datacube-ows--993.org.readthedocs.build/en/993/
=> For 1 8 37

check-code-all.sh, datacube_ows/data.py, datacube_ows/ows_configuration.py
This should render our feature_info output geojson compliant.
Also remove reference to `update_ranges` in error messages
Also update test db setup to reflect DEA collection changes.
Closes #892 and #985
----
📚 Documentation preview 📚: https://datacube-ows--995.org.readthedocs.build/en/995/
=> Make feature info output GeoJSON compatible.

datacube_ows/sql/extent_views/create/011_create_new_space_view_raw.sql, datacube_ows/templates/wmts_capabilities.xml
The space materialised view definition previously required all supported metadata types to be explicitly included in the view definition.  A catch-all has been added for all metadata types starting with `eo3_`.
Note that a non-eo3-compatible metadata type with a name starting with `eo3_` will now break OWS, but this is better than any metadata type with a name not in  a whitelist breaking OWS.
Also fixes a bug in WMTS - exposed by more thorough WMTS validation in newer versions of OWSLib.
----
📚 Documentation preview 📚: https://datacube-ows--996.org.readthedocs.build/en/996/
=> Generalise eo3-compatible product handling in materialised view definition

HISTORY.rst, datacube_ows/__init__.py
Update default version number and version history.
----
📚 Documentation preview 📚: https://datacube-ows--997.org.readthedocs.build/en/997/
=> For 1.8.38 release.

HISTORY.rst, datacube_ows/__init__.py, datacube_ows/sql/extent_views/create/010_create_new_time_view.sql
The Space view changes in #996 don't work without these parallel changes in the time view.
Plus ready for 1.8.39 release.
----
📚 Documentation preview 📚: https://datacube-ows--999.org.readthedocs.build/en/999/
=> Eo3 generalised in Time MV - and 1.8.39 release

datacube_ows/data.py
Fix data load for partially broken products. Closes #1000 .
----
📚 Documentation preview 📚: https://datacube-ows--1001.org.readthedocs.build/en/1001/
=> #1000 Skip broken datasets during load

setup.py
This fixes CVE-2021-34141.
----
📚 Documentation preview 📚: https://datacube-ows--1005.org.readthedocs.build/en/1005/
=> Update to numpy 1.22

setup.py
This fixes CVE-2024-1135.
----
📚 Documentation preview 📚: https://datacube-ows--1008.org.readthedocs.build/en/1008/
=> Update to gunicorn 22.0.0

datacube_ows/data.py
Data links for STAC indexed products currently point to the STAC JSON file, rather than being redirected to the overall data folder like we do for YAML files:
This PR attempts to fix this by editing the regex that is used to identify the S3 folder to include JSON files.
----
📚 Documentation preview 📚: https://datacube-ows--1011.org.readthedocs.build/en/1011/
=> Fix data links for products indexed with STAC metadata

HISTORY.rst, datacube_ows/__init__.py, datacube_ows/data.py, integration_tests/utils.py, tests/test_data.py
Ready for 1.8.40 release.
* Increment default version number
* Update HISTORY.rst
* Add unit test for Robbi's PR #1011
* Reformatting to keep lint happy.
----
📚 Documentation preview 📚: https://datacube-ows--1013.org.readthedocs.build/en/1013/
=> Prep for 1.8.40 release

.github/ISSUE_TEMPLATE/ISSUE_TEMPLATE.md, datacube_ows/sql/postgres/ows_schema/grants/read_only/002_grant_range_read_requires_role.sql, datacube_ows/sql/postgres/ows_schema/grants/read_only/003_grant_agdc_user_requires_role.sql, datacube_ows/templates/wms_capabilities.xml, datacube_ows/wcs1_utils.py, datacube_ows/wcs_scaler.py, integration_tests/test_wcs_server.py, tests/test_wcs_scaler.py
* Check for error after retrieving ranges.
* Use correct dtype when writing out empty data in WCS1 (not required in WCS2).
* Update issue template.
* Ensure correct default behaviour when output and subsetting CRSs match.
* Add (very simple) test.
(cherry picked from commit 79b796fd6b76b76c4274094644a14b50c72b0413)
PLUS:
* Plug some gaps in permissions management
* Fix some WCS Scaler code that was broken in previous 1.9 PRs, and the corresponding unit tests.
----
📚 Documentation preview 📚: https://datacube-ows--1028.org.readthedocs.build/en/1028/
=> WCS fixes. (cherry pick of PR #1027 to 1.9 branch)

datacube_ows/band_utils.py, datacube_ows/styles/component.py, datacube_ows/styles/ramp.py, docs/cfg_colourramp_styles.rst, integration_tests/cfg/ows_test_cfg.py, wordlist.txt
Fixes #1007
In a multi-date handler for colour-ramp-type styles: a new `pass_raw_data` config entry controls what data is passed to the aggregator function:
`pass_raw_data == False` (the default):
The aggregator function is passed a time-dimensioned DataArray containing the output
of the index function.
`pass_raw_data == True`:
The aggregator function is passed a time-dimensioned Dataset, containing all of the
declared needed bands.
----
📚 Documentation preview 📚: https://datacube-ows--1033.org.readthedocs.build/en/1033/
=> multi-date handler aggregator in ramp styles can now receive raw data

HISTORY.rst, datacube_ows/__init__.py
Increment default version number and update HISTORY.rst for release.
----
📚 Documentation preview 📚: https://datacube-ows--1034.org.readthedocs.build/en/1034/
=> Prep for 1.8.41 release.

Dockerfile
This fixes the warning:
- FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 2)
emitted by recent Docker releases.
----
📚 Documentation preview 📚: https://datacube-ows--1035.org.readthedocs.build/en/1035/
=> Dockerfile: fix casing warning

README.rst, datacube_ows/sql/extent_views/create/011_create_new_space_view_raw.sql
As discussed in #1002, creation of OWS materialised views fails on indexes that contain datasets with WKT-format CRSs, even if the datasets in question belong to products not included in the OWS config.
This PR explicitly excludes non-EPSG CRS datasets from the materialised view.  This means that such datasets can NEVER be returned by OWS, but it will at least be able to possible to use OWS for other products in the same index.
Viewing non-EPSG CRS datasets will be possible in 1.9.0, with the new postgis ODC driver.
This (and other CRS-related) limitations of 1.8/postgres OWS are now documented in the README.
----
📚 Documentation preview 📚: https://datacube-ows--1037.org.readthedocs.build/en/1037/
=> Changes to materialised view definition to prevent errors on databases with WKT CRSs

datacube_ows/data.py, datacube_ows/ows_configuration.py, datacube_ows/styles/base.py, datacube_ows/wms_utils.py, docs/cfg_layers.rst, docs/cfg_styling.rst, docs/conf.py, docs/index.rst, integration_tests/cfg/ows_test_cfg.py, integration_tests/cfg/utils.py, integration_tests/conftest.py, integration_tests/test_wms_server.py, wordlist.txt
Significant overhaul of custom feature info includes.
1) Old `include_custom` entries still supported by deprecated.
2) New `custom_includes` entries, similar to the old `include_custom`,  but:
a) Get passed a single-date xarray Dataset (for data) and an ODC Dataset (for metadata) (instead of a dictionary for data) 
b) Can be defined at the layer or the style level (Style overrides layer if both are provided)
3) New multi-date `custom_includes` entry at the multi-date handler level:
* Gets passed a multi-date xarray Dataset (no metadata).
Fixes #983 and provides multi-date behaviour requested by @robbibt 
----
📚 Documentation preview 📚: https://datacube-ows--1039.org.readthedocs.build/en/1039/
=> Feature info enhancements

Dockerfile, HISTORY.rst, README.rst, datacube_ows/__init__.py, datacube_ows/band_utils.py, datacube_ows/config_utils.py, datacube_ows/feature_info.py, datacube_ows/ows_configuration.py, datacube_ows/sql/postgres/extent_views/create/011_create_new_space_view.sql, datacube_ows/styles/base.py, datacube_ows/styles/ramp.py, datacube_ows/templates/wms_capabilities.xml, datacube_ows/wms_utils.py, datacube_ows/wsgi.py, docs/cfg_colourramp_styles.rst, docs/cfg_layers.rst, docs/cfg_styling.rst, docs/conf.py, docs/index.rst, integration_tests/cfg/ows_test_cfg.py, integration_tests/cfg/utils.py, integration_tests/conftest.py, integration_tests/test_wms_server.py, wordlist.txt
Forward-ports of #1022, #1033, #1034, #1035, #1036, #1037 and #1039 from the 1.8 branch (`master`) to 1.9.
----
📚 Documentation preview 📚: https://datacube-ows--1040.org.readthedocs.build/en/1040/
=> Cherry picks from 1.8

HISTORY.rst, datacube_ows/__init__.py, docs/cfg_styling.rst, wordlist.txt
Update default version number and HISTORY.rst for 1.9.0-rc1 release.
Fix documentation typos fixed in #1042 in 1.8.
----
📚 Documentation preview 📚: https://datacube-ows--1044.org.readthedocs.build/en/1044/
=> For 1.9.0 rc1

HISTORY.rst, datacube_ows/__init__.py
Ready for a 1.8.42 release.
----
📚 Documentation preview 📚: https://datacube-ows--1043.org.readthedocs.build/en/1043/
=> Update default version number and HISTORY.rst for 1.8.42 release.

.github/workflows/complementary-config-test.yaml, .github/workflows/pyspy-profiling.yaml, .github/workflows/test-prod.yaml, .github/workflows/test.yml, Dockerfile, docker-compose.yaml, docker/files/remap-user.sh
Add a script for switching UID/GID
of the user inside the container.
Use this to avoid making the directories
the CI uses world-writable.
----
📚 Documentation preview 📚: https://datacube-ows--1047.org.readthedocs.build/en/1047/
=> Dockerfile: enable switching UID/GID

.github/workflows/lint.yml, .github/workflows/pyspy-profiling.yaml, .github/workflows/test-prod.yaml
The set-output command has been
deprecated for a couple of years
by now, switch to using GITHUB_OUTPUT
to reduce the noise in the CI logs.
----
📚 Documentation preview 📚: https://datacube-ows--1052.org.readthedocs.build/en/1052/
=> CI: stop using set-output

Dockerfile, docker-compose.prod.yaml, docker/files/remap-user.sh
Make the minimal change to mirror
the change from datacube-explorer's
update to GDAL 3.9.
----
📚 Documentation preview 📚: https://datacube-ows--1046.org.readthedocs.build/en/1046/
=> Dockerfile: update to GDAL 3.9.1

.github/workflows/complementary-config-test.yaml, .github/workflows/pyspy-profiling.yaml, .github/workflows/test.yml
Only execute the script if the cd
was successful. This prevents the CI
from accidentally passing if there
is a script with the same name in
the default work directory.
----
📚 Documentation preview 📚: https://datacube-ows--1053.org.readthedocs.build/en/1053/
=> CI: check return values of cd

datacube_ows/wcs1_utils.py, datacube_ows/wcs2_utils.py
This came up while I was working on #1041 and @SpacemanPaul asked me to PR it :)
----
📚 Documentation preview 📚: https://datacube-ows--1054.org.readthedocs.build/en/1054/
=> Fix TIFF statistics in case WCS output has NaNs

.pre-commit-config.yaml, datacube_ows/wcs1_utils.py, datacube_ows/wcs2_utils.py
Cherry picking @christophfriedrich 's #1054 and pre-commit's #1029.
----
📚 Documentation preview 📚: https://datacube-ows--1056.org.readthedocs.build/en/1056/
=> Cherry picks of recent PRs to 1.9

Dockerfile
After adding health checks to docker compose,
this command is no longer used anywhere else.
----
📚 Documentation preview 📚: https://datacube-ows--1057.org.readthedocs.build/en/1057/
=> Dockerfile: remove pg_isready

.github/workflows/test.yml, Dockerfile, docker-compose.yaml
Only install the test dependencies in
in the image used by the CI.
----
📚 Documentation preview 📚: https://datacube-ows--1059.org.readthedocs.build/en/1059/
=> Dockerfile: remove test deps from prod image

Dockerfile, docker-compose.prod.yaml
This setting only applies to gthread
according to the documentation:
https://docs.gunicorn.org/en/23.0.0/settings.html#threads
----
📚 Documentation preview 📚: https://datacube-ows--1061.org.readthedocs.build/en/1061/
=> Stop passing --threads to gunicorn
